<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><IsPackable>false</IsPackable>
    <AssemblyName>SharpLink.Benchmarks</AssemblyName><ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../src/SharpLink.Server/SharpLink.Server.csproj" />
    <ProjectReference Include="../../../../src/SharpLink.Client/SharpLink.Client.csproj" />
    <ProjectReference Include="../../../../src/SharpLink.Runtime/SharpLink.Runtime.csproj" />
    <ProjectReference Include="../../../../src/SharpLink.Sdk/SharpLink.Sdk.csproj" />
  </ItemGroup>
</Project>
