<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharpLink.Abstractions\SharpLink.Abstractions.csproj" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="SharpLink.UnitTests" />
      <InternalsVisibleTo Include="SharpLink.Client" />
      <InternalsVisibleTo Include="SharpLink.Server" />
    </ItemGroup>

</Project>
