namespace SharpLink.Abstractions;

/// <summary>Identifies how one generated Codec factory obtains its Codec instance.</summary>
public enum RpcGeneratedCodecFactoryKind
{
    /// <summary>The Codec is generated by SharpLink and uses the native wire format.</summary>
    Native = 0,

    /// <summary>The Codec is created through an <see cref="IRpcCodecAdapter"/> scope.</summary>
    Adapter = 1,

    /// <summary>The Codec is a compile-time selected closed <see cref="IRpcCodec{T}"/> implementation.</summary>
    Direct = 2
}

/// <summary>Creates one source-generated Codec for an immutable runtime-context snapshot.</summary>
public interface IRpcGeneratedCodecFactory
{
    /// <summary>Gets the closed DTO or collection type handled by the factory.</summary>
    Type TargetType { get; }

    /// <summary>Gets the deterministic schema identifier used for idempotent registration.</summary>
    string SchemaId { get; }

    /// <summary>Gets the stable binary wire-format identity.</summary>
    string WireFormatId { get; }

    /// <summary>Gets how this factory obtains its Codec instance.</summary>
    RpcGeneratedCodecFactoryKind Kind => AdapterId is null
        ? RpcGeneratedCodecFactoryKind.Native
        : RpcGeneratedCodecFactoryKind.Adapter;

    /// <summary>Gets the adapter lifecycle identity, or null when no adapter scope is used.</summary>
    string? AdapterId { get; }

    /// <summary>Gets the adapter instance, or null when no adapter scope is used.</summary>
    IRpcCodecAdapter? Adapter { get; }

    /// <summary>Creates a Codec whose dependencies are resolved from the target Context.</summary>
    /// <param name="provider">The target Context Codec provider.</param>
    /// <param name="adapterScope">The context-owned adapter scope, or <see langword="null"/> when no adapter is used.</param>
    IRpcCodec Create(IRpcCodecProvider provider, IRpcCodecAdapterScope? adapterScope);

    /// <summary>Checks the closed Codec interface without runtime type construction or scanning.</summary>
    bool IsCompatibleCodec(IRpcCodec codec);
}
