namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateCodecs(ImmutableArray<GeneratedCodecModel> codecs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();

        foreach (var adapter in codecs
                     .Where(static codec => codec.Kind == GeneratedCodecKind.Adapter)
                     .GroupBy(static codec => codec.AdapterId, StringComparer.Ordinal)
                     .Select(static group => group.First())
                     .OrderBy(static codec => codec.AdapterId, StringComparer.Ordinal))
        {
            sb.AppendLine($"internal static class {GetAdapterHolderName(adapter.AdapterId!)}");
            sb.AppendLine("{");
            sb.AppendLine($"    internal static readonly IRpcCodecAdapter Instance = new {adapter.AdapterType}();");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        foreach (var codec in codecs)
        {
            if (codec.Kind == GeneratedCodecKind.Adapter)
                AppendAdapterCodecFactory(sb, codec);
            else if (codec.Kind == GeneratedCodecKind.Direct)
                AppendDirectCodecFactory(sb, codec);
            else if (codec.Kind == GeneratedCodecKind.Dto)
                AppendDtoCodec(sb, codec);
            else
                AppendCollectionCodec(sb, codec);
        }

        return sb.ToString();
    }

    private static void AppendAdapterCodecFactory(StringBuilder sb, GeneratedCodecModel model)
    {
        sb.AppendLine($"internal static class {model.CodecName}");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed class Factory : IRpcGeneratedCodecFactory");
        sb.AppendLine("    {");
        sb.AppendLine($"        public Type TargetType => typeof({model.TypeName});");
        sb.AppendLine($"        public string SchemaId => \"{EscapeString(model.SchemaId)}\";");
        sb.AppendLine($"        public string WireFormatId => \"{EscapeString(model.WireFormatId)}\";");
        sb.AppendLine($"        public string? AdapterId => \"{EscapeString(model.AdapterId!)}\";");
        sb.AppendLine($"        public IRpcCodecAdapter Adapter => {GetAdapterHolderName(model.AdapterId!)}.Instance;");
        sb.AppendLine("        public IRpcCodec Create(IRpcCodecProvider provider, IRpcCodecAdapterScope? adapterScope)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(provider);");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(adapterScope);");
        sb.AppendLine($"            return adapterScope.CreateCodec<{model.TypeName}>();");
        sb.AppendLine("        }");
        sb.AppendLine($"        public bool IsCompatibleCodec(IRpcCodec codec) => codec is IRpcCodec<{model.TypeName}>;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDirectCodecFactory(StringBuilder sb, GeneratedCodecModel model)
    {
        sb.AppendLine($"internal static class {model.CodecName}");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed class Factory : IRpcGeneratedCodecFactory");
        sb.AppendLine("    {");
        sb.AppendLine($"        public Type TargetType => typeof({model.TypeName});");
        sb.AppendLine($"        public string SchemaId => \"{EscapeString(model.SchemaId)}\";");
        sb.AppendLine($"        public string WireFormatId => \"{EscapeString(model.WireFormatId)}\";");
        sb.AppendLine("        public RpcGeneratedCodecFactoryKind Kind => RpcGeneratedCodecFactoryKind.Direct;");
        sb.AppendLine("        public string? AdapterId => null;");
        sb.AppendLine("        public IRpcCodecAdapter? Adapter => null;");
        sb.AppendLine("        public IRpcCodec Create(IRpcCodecProvider provider, IRpcCodecAdapterScope? adapterScope)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(provider);");
        sb.AppendLine("            if (adapterScope is not null)");
        sb.AppendLine("                throw new ArgumentException(\"Direct Codec factories do not accept an adapter scope.\", nameof(adapterScope));");
        sb.AppendLine($"            return new {model.AdapterType}();");
        sb.AppendLine("        }");
        sb.AppendLine($"        public bool IsCompatibleCodec(IRpcCodec codec) => codec is IRpcCodec<{model.TypeName}>;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string GetAdapterHolderName(string adapterId)
        => "__SharpLinkGeneratedAdapter_" + ComputeEmitterHash(adapterId).ToString("X16", InvariantCulture);

    private static ulong ComputeEmitterHash(string value)
    {
        const ulong offset = 14695981039346656037UL;
        const ulong prime = 1099511628211UL;
        var hash = offset;
        foreach (var character in value)
        {
            hash ^= character;
            hash *= prime;
        }
        return hash;
    }

    private static void AppendDtoCodec(StringBuilder sb, GeneratedCodecModel model)
    {
        var complexMembers = model.Members
            .Where(static member => member.Kind == GeneratedMemberKind.Complex)
            .ToArray();
        var complexIndexes = new Dictionary<string, int>(StringComparer.Ordinal);
        for (var index = 0; index < complexMembers.Length; index++)
            complexIndexes.Add(complexMembers[index].Name, index);

        sb.AppendLine($"internal sealed class {model.CodecName} : IRpcCodec<{model.TypeName}>");
        sb.AppendLine("{");
        for (var index = 0; index < complexMembers.Length; index++)
            sb.AppendLine($"    private readonly IRpcCodec<{complexMembers[index].TypeName}> __codec_{index};");
        sb.AppendLine();
        sb.AppendLine($"    internal {model.CodecName}(IRpcCodecProvider provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(provider);");
        for (var index = 0; index < complexMembers.Length; index++)
            sb.AppendLine($"        __codec_{index} = provider.GetCodec<{complexMembers[index].TypeName}>();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Serialize(in {model.TypeName} value, IBufferWriter<byte> writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(writer);");
        if (complexMembers.Length != 0)
        {
            sb.AppendLine("        var rpcWriter = writer as IRpcByteBufferWriter ?? throw new InvalidOperationException(\"Generated DTO Codecs require the SharpLink packet writer.\");");
        }
        if (model.IsReferenceType)
        {
            sb.AppendLine("        if (value is null)");
            sb.AppendLine("        {");
            sb.AppendLine("            RpcGeneratedCodecWire.WritePresence(writer, false);");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine("        RpcGeneratedCodecWire.WritePresence(writer, true);");
        }
        foreach (var member in model.Members)
            AppendDtoMemberWrite(sb, member, complexIndexes);
        sb.AppendLine("        RpcGeneratedCodecWire.WriteObjectEnd(writer);");
        sb.AppendLine("    }");
        sb.AppendLine();

        var returnType = model.IsReferenceType ? model.TypeName + "?" : model.TypeName;
        sb.AppendLine($"    public {returnType} Deserialize(in ReadOnlySequence<byte> buffer)");
        sb.AppendLine("    {");
        sb.AppendLine("        var reader = new SequenceReader<byte>(buffer);");
        if (model.IsReferenceType)
        {
            sb.AppendLine("        if (!RpcGeneratedCodecWire.ReadPresence(ref reader))");
            sb.AppendLine("        {");
            sb.AppendLine("            RpcGeneratedCodecWire.EnsureFullyConsumed(reader);");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
        }
        foreach (var member in model.Members)
        {
            sb.AppendLine($"        {member.TypeName} local_{member.Identifier} = default!;");
            if (member.Required)
                sb.AppendLine($"        var seen_{member.Identifier} = false;");
        }
        sb.AppendLine("        while (RpcGeneratedCodecWire.TryReadField(ref reader, out var fieldId, out var wireType))");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (fieldId)");
        sb.AppendLine("            {");
        foreach (var member in model.Members)
            AppendDtoMemberRead(sb, member, complexIndexes);
        sb.AppendLine("                default:");
        sb.AppendLine("                    RpcGeneratedCodecWire.SkipField(ref reader, wireType);");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        RpcGeneratedCodecWire.EnsureFullyConsumed(reader);");
        foreach (var member in model.Members.Where(static member => member.Required))
        {
            sb.AppendLine($"        if (!seen_{member.Identifier})");
            sb.AppendLine($"            throw RpcGeneratedCodecWire.DataLoss(\"Missing required RPC member '{EscapeString(member.Name)}'.\");");
            if (member.NonNullableReference)
            {
                sb.AppendLine($"        if (local_{member.Identifier} is null)");
                sb.AppendLine($"            throw RpcGeneratedCodecWire.DataLoss(\"Required RPC member '{EscapeString(member.Name)}' cannot be null.\");");
            }
        }

        var memberByName = model.Members.ToDictionary(static member => member.Name, StringComparer.Ordinal);
        sb.Append($"        return new {model.TypeName}(");
        for (var index = 0; index < model.ConstructorMembers.Length; index++)
        {
            if (index != 0)
                sb.Append(", ");
            sb.Append("local_").Append(memberByName[model.ConstructorMembers[index]].Identifier);
        }
        sb.Append(')');
        var initializerMembers = model.Members.Where(static member => member.InitializerBound).ToArray();
        if (initializerMembers.Length != 0)
        {
            sb.AppendLine();
            sb.AppendLine("        {");
            for (var index = 0; index < initializerMembers.Length; index++)
            {
                var member = initializerMembers[index];
                var suffix = index == initializerMembers.Length - 1 ? string.Empty : ",";
                sb.AppendLine($"            {EscapeIdentifier(member.Identifier)} = local_{member.Identifier}{suffix}");
            }
            sb.Append("        }");
        }
        sb.AppendLine(";");
        sb.AppendLine("    }");
        AppendFactory(sb, model);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDtoMemberWrite(
        StringBuilder sb,
        GeneratedMemberModel member,
        Dictionary<string, int> complexIndexes)
    {
        var value = $"value.{EscapeIdentifier(member.Identifier)}";
        var fieldId = member.FieldId.ToString(InvariantCulture) + "U";
        switch (member.Kind)
        {
            case GeneratedMemberKind.Fixed:
                sb.AppendLine($"        RpcGeneratedCodecWire.WriteFieldKey(writer, {fieldId}, {GetWireType(member.FixedSize)});");
                sb.AppendLine(GetFixedWriteExpression(member.TypeName, value, 8));
                break;
            case GeneratedMemberKind.NullableFixed:
                sb.AppendLine($"        if (!{value}.HasValue)");
                sb.AppendLine($"            RpcGeneratedCodecWire.WriteFieldKey(writer, {fieldId}, RpcGeneratedWireType.Null);");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            RpcGeneratedCodecWire.WriteFieldKey(writer, {fieldId}, {GetWireType(member.FixedSize)});");
                sb.AppendLine(GetFixedWriteExpression(member.FixedTypeName!, value + ".Value", 12));
                sb.AppendLine("        }");
                break;
            case GeneratedMemberKind.String:
                sb.AppendLine($"        if ({value} is null)");
                sb.AppendLine($"            RpcGeneratedCodecWire.WriteFieldKey(writer, {fieldId}, RpcGeneratedWireType.Null);");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            RpcGeneratedCodecWire.WriteFieldKey(writer, {fieldId}, RpcGeneratedWireType.LengthDelimited);");
                sb.AppendLine($"            RpcGeneratedCodecWire.WriteString(writer, {value});");
                sb.AppendLine("        }");
                break;
            default:
                var index = complexIndexes[member.Name];
                sb.AppendLine($"        RpcGeneratedCodecWire.WriteFieldKey(writer, {fieldId}, RpcGeneratedWireType.LengthDelimited);");
                sb.AppendLine("        var lengthToken_" + index + " = RpcGeneratedCodecWire.BeginLength(rpcWriter);");
                sb.AppendLine($"        __codec_{index}.Serialize({value}, writer);");
                sb.AppendLine("        RpcGeneratedCodecWire.EndLength(rpcWriter, lengthToken_" + index + ");");
                break;
        }
    }

    private static void AppendDtoMemberRead(
        StringBuilder sb,
        GeneratedMemberModel member,
        Dictionary<string, int> complexIndexes)
    {
        sb.AppendLine($"                case {member.FieldId.ToString(InvariantCulture)}U:");
        if (member.Required)
            sb.AppendLine($"                    seen_{member.Identifier} = true;");
        switch (member.Kind)
        {
            case GeneratedMemberKind.Fixed:
                sb.AppendLine($"                    RpcGeneratedCodecWire.EnsureWireType(wireType, {GetWireType(member.FixedSize)});");
                sb.AppendLine(GetFixedReadExpression(member.TypeName, $"local_{member.Identifier}", 20));
                break;
            case GeneratedMemberKind.NullableFixed:
                sb.AppendLine("                    if (wireType == RpcGeneratedWireType.Null)");
                sb.AppendLine($"                        local_{member.Identifier} = default;");
                sb.AppendLine("                    else");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        RpcGeneratedCodecWire.EnsureWireType(wireType, {GetWireType(member.FixedSize)});");
                sb.AppendLine(GetFixedReadExpression(member.FixedTypeName!, $"local_{member.Identifier}", 24));
                sb.AppendLine("                    }");
                break;
            case GeneratedMemberKind.String:
                sb.AppendLine("                    if (wireType == RpcGeneratedWireType.Null)");
                sb.AppendLine($"                        local_{member.Identifier} = null!;");
                sb.AppendLine("                    else");
                sb.AppendLine("                    {");
                sb.AppendLine("                        RpcGeneratedCodecWire.EnsureWireType(wireType, RpcGeneratedWireType.LengthDelimited);");
                sb.AppendLine($"                        local_{member.Identifier} = RpcGeneratedCodecWire.ReadString(ref reader);");
                sb.AppendLine("                    }");
                break;
            default:
                var index = complexIndexes[member.Name];
                sb.AppendLine("                    RpcGeneratedCodecWire.EnsureWireType(wireType, RpcGeneratedWireType.LengthDelimited);");
                sb.AppendLine($"                    local_{member.Identifier} = __codec_{index}.Deserialize(RpcGeneratedCodecWire.ReadLengthDelimited(ref reader))!;");
                break;
        }
        sb.AppendLine("                    break;");
    }

    private static string GetFixedWriteExpression(string typeName, string value, int spaces)
    {
        var indent = new string(' ', spaces);
        if (IsBooleanType(typeName))
            return $"{indent}RpcGeneratedCodecWire.WriteBoolean(writer, {value});";
        var semanticMethod = GetSemanticFixedMethod(typeName);
        return semanticMethod is null
            ? $"{indent}RpcGeneratedCodecWire.WriteUnmanaged<{typeName}>(writer, {value});"
            : $"{indent}RpcGeneratedCodecWire.Write{semanticMethod}(writer, {value});";
    }

    private static string GetFixedReadExpression(string typeName, string target, int spaces)
    {
        var indent = new string(' ', spaces);
        if (IsBooleanType(typeName))
            return $"{indent}{target} = RpcGeneratedCodecWire.ReadBoolean(ref reader);";
        var semanticMethod = GetSemanticFixedMethod(typeName);
        return semanticMethod is null
            ? $"{indent}{target} = RpcGeneratedCodecWire.ReadUnmanaged<{typeName}>(ref reader);"
            : $"{indent}{target} = RpcGeneratedCodecWire.Read{semanticMethod}(ref reader);";
    }

    private static string? GetSemanticFixedMethod(string typeName)
        => typeName.Replace("global::", string.Empty) switch
        {
            "System.Text.Rune" => "Rune",
            "decimal" or "System.Decimal" => "Decimal",
            "System.DateOnly" => "DateOnly",
            "System.DateTime" => "DateTime",
            "System.TimeOnly" => "TimeOnly",
            "System.DateTimeOffset" => "DateTimeOffset",
            _ => null
        };

    private static void AppendCollectionCodec(StringBuilder sb, GeneratedCodecModel model)
    {
        sb.AppendLine($"internal sealed class {model.CodecName} : IRpcCodec<{model.TypeName}>");
        sb.AppendLine("{");
        if (model.Kind == GeneratedCodecKind.Dictionary)
        {
            sb.AppendLine($"    private readonly IRpcCodec<{model.KeyType}> __keyCodec;");
            sb.AppendLine($"    private readonly IRpcCodec<{model.ValueType}> __valueCodec;");
        }
        else
        {
            sb.AppendLine($"    private readonly IRpcCodec<{model.ElementType}> __elementCodec;");
        }
        sb.AppendLine();
        sb.AppendLine($"    internal {model.CodecName}(IRpcCodecProvider provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(provider);");
        if (model.Kind == GeneratedCodecKind.Dictionary)
        {
            sb.AppendLine($"        __keyCodec = provider.GetCodec<{model.KeyType}>();");
            sb.AppendLine($"        __valueCodec = provider.GetCodec<{model.ValueType}>();");
        }
        else
        {
            sb.AppendLine($"        __elementCodec = provider.GetCodec<{model.ElementType}>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Serialize(in {model.TypeName} value, IBufferWriter<byte> writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(writer);");
        sb.AppendLine("        var rpcWriter = writer as IRpcByteBufferWriter ?? throw new InvalidOperationException(\"Generated collection Codecs require the SharpLink packet writer.\");");
        AppendCollectionWrite(sb, model);
        sb.AppendLine("    }");
        sb.AppendLine();
        var returnType = model.IsReferenceType ? model.TypeName + "?" : model.TypeName;
        sb.AppendLine($"    public {returnType} Deserialize(in ReadOnlySequence<byte> buffer)");
        sb.AppendLine("    {");
        AppendCollectionRead(sb, model);
        sb.AppendLine("    }");
        AppendFactory(sb, model);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendCollectionWrite(StringBuilder sb, GeneratedCodecModel model)
    {
        if (model.Kind == GeneratedCodecKind.Nullable)
        {
            sb.AppendLine("        if (!value.HasValue)");
            sb.AppendLine("        {");
            sb.AppendLine("            RpcGeneratedCodecWire.WritePresence(writer, false);");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine("        RpcGeneratedCodecWire.WritePresence(writer, true);");
            sb.AppendLine("        __elementCodec.Serialize(value.Value, writer);");
            return;
        }

        var nullCondition = model.Kind switch
        {
            GeneratedCodecKind.Array or GeneratedCodecKind.List or GeneratedCodecKind.Dictionary => "value is null",
            GeneratedCodecKind.ImmutableArray => "value.IsDefault",
            _ => null
        };
        if (nullCondition is not null)
        {
            sb.AppendLine($"        if ({nullCondition})");
            sb.AppendLine("        {");
            sb.AppendLine("            RpcGeneratedCodecWire.WriteCollectionCount(writer, 0, true);");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
        }
        var countExpression = model.Kind == GeneratedCodecKind.Dictionary ? "value.Count" : "value.Length";
        if (model.Kind == GeneratedCodecKind.List)
            countExpression = "value.Count";
        sb.AppendLine($"        RpcGeneratedCodecWire.WriteCollectionCount(writer, {countExpression}, false);");

        if (model.Kind == GeneratedCodecKind.Dictionary)
        {
            sb.AppendLine("        foreach (var pair in value)");
            sb.AppendLine("        {");
            AppendLengthWrappedWrite(sb, "__keyCodec", "pair.Key", "key", 12);
            AppendLengthWrappedWrite(sb, "__valueCodec", "pair.Value", "value", 12);
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine($"        for (var index = 0; index < {countExpression}; index++)");
        sb.AppendLine("        {");
        var itemExpression = model.Kind is GeneratedCodecKind.Memory or GeneratedCodecKind.ReadOnlyMemory
            ? "value.Span[index]"
            : "value[index]";
        sb.AppendLine($"            var item = {itemExpression};");
        AppendLengthWrappedWrite(sb, "__elementCodec", "item", "item", 12);
        sb.AppendLine("        }");
    }

    private static void AppendLengthWrappedWrite(
        StringBuilder sb,
        string codec,
        string value,
        string suffix,
        int spaces)
    {
        var indent = new string(' ', spaces);
        sb.AppendLine($"{indent}var {suffix}LengthToken = RpcGeneratedCodecWire.BeginLength(rpcWriter);");
        sb.AppendLine($"{indent}{codec}.Serialize({value}, writer);");
        sb.AppendLine($"{indent}RpcGeneratedCodecWire.EndLength(rpcWriter, {suffix}LengthToken);");
    }

    private static void AppendCollectionRead(StringBuilder sb, GeneratedCodecModel model)
    {
        sb.AppendLine("        var reader = new SequenceReader<byte>(buffer);");
        if (model.Kind == GeneratedCodecKind.Nullable)
        {
            sb.AppendLine("        if (!RpcGeneratedCodecWire.ReadPresence(ref reader))");
            sb.AppendLine("        {");
            sb.AppendLine("            RpcGeneratedCodecWire.EnsureFullyConsumed(reader);");
            sb.AppendLine("            return default;");
            sb.AppendLine("        }");
            sb.AppendLine("        var item = __elementCodec.Deserialize(reader.Sequence.Slice(reader.Position));");
            sb.AppendLine("        return item;");
            return;
        }

        sb.AppendLine("        var count = RpcGeneratedCodecWire.ReadCollectionCount(ref reader);");
        sb.AppendLine("        if (count < 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            RpcGeneratedCodecWire.EnsureFullyConsumed(reader);");
        if (model.Kind is GeneratedCodecKind.Array or GeneratedCodecKind.List or GeneratedCodecKind.Dictionary)
            sb.AppendLine("            return null;");
        else
            sb.AppendLine("            return default;");
        sb.AppendLine("        }");

        if (model.Kind == GeneratedCodecKind.Dictionary)
        {
            sb.AppendLine($"        var result = new {model.TypeName}(count);");
            sb.AppendLine("        for (var index = 0; index < count; index++)");
            sb.AppendLine("        {");
            sb.AppendLine("            var key = __keyCodec.Deserialize(RpcGeneratedCodecWire.ReadLengthDelimited(ref reader));");
            sb.AppendLine("            var value = __valueCodec.Deserialize(RpcGeneratedCodecWire.ReadLengthDelimited(ref reader));");
            sb.AppendLine("            if (key is null)");
            sb.AppendLine("                throw RpcGeneratedCodecWire.DataLoss(\"Generated dictionary contains a null key.\");");
            sb.AppendLine("            if (!result.TryAdd(key!, value!))");
            sb.AppendLine("                throw RpcGeneratedCodecWire.DataLoss(\"Generated dictionary contains a duplicate key.\");");
            sb.AppendLine("        }");
            sb.AppendLine("        RpcGeneratedCodecWire.EnsureFullyConsumed(reader);");
            sb.AppendLine("        return result;");
            return;
        }

        if (model.Kind == GeneratedCodecKind.List)
        {
            sb.AppendLine($"        var result = new {model.TypeName}(count);");
            sb.AppendLine("        for (var index = 0; index < count; index++)");
            sb.AppendLine("            result.Add(__elementCodec.Deserialize(RpcGeneratedCodecWire.ReadLengthDelimited(ref reader))!);");
            sb.AppendLine("        RpcGeneratedCodecWire.EnsureFullyConsumed(reader);");
            sb.AppendLine("        return result;");
            return;
        }

        sb.AppendLine($"        var items = new {GetArrayCreationType(model.ElementType!, "count")};");
        sb.AppendLine("        for (var index = 0; index < count; index++)");
        sb.AppendLine("            items[index] = __elementCodec.Deserialize(RpcGeneratedCodecWire.ReadLengthDelimited(ref reader))!;");
        sb.AppendLine("        RpcGeneratedCodecWire.EnsureFullyConsumed(reader);");
        var returnExpression = model.Kind switch
        {
            GeneratedCodecKind.Array => "items",
            GeneratedCodecKind.Memory => $"new {model.TypeName}(items)",
            GeneratedCodecKind.ReadOnlyMemory => $"new {model.TypeName}(items)",
            GeneratedCodecKind.ImmutableArray => "ImmutableArray.CreateRange(items)",
            _ => "items"
        };
        sb.AppendLine($"        return {returnExpression};");
    }

    private static void AppendFactory(StringBuilder sb, GeneratedCodecModel model)
    {
        sb.AppendLine();
        sb.AppendLine("    internal sealed class Factory : IRpcGeneratedCodecFactory");
        sb.AppendLine("    {");
        sb.AppendLine($"        public Type TargetType => typeof({model.TypeName});");
        sb.AppendLine($"        public string SchemaId => \"{EscapeString(model.SchemaId)}\";");
        sb.AppendLine("        public string WireFormatId => \"sharplink-native/v1\";");
        sb.AppendLine("        public string? AdapterId => null;");
        sb.AppendLine("        public IRpcCodecAdapter? Adapter => null;");
        sb.AppendLine($"        public IRpcCodec Create(IRpcCodecProvider provider, IRpcCodecAdapterScope? adapterScope)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (adapterScope is not null)");
        sb.AppendLine("                throw new ArgumentException(\"Native Codec factories do not accept an adapter scope.\", nameof(adapterScope));");
        sb.AppendLine($"            return new {model.CodecName}(provider);");
        sb.AppendLine("        }");
        sb.AppendLine($"        public bool IsCompatibleCodec(IRpcCodec codec) => codec is IRpcCodec<{model.TypeName}>;");
        sb.AppendLine("    }");
    }

    private static string GetWireType(int fixedSize) => fixedSize switch
    {
        1 => "RpcGeneratedWireType.Fixed1",
        2 => "RpcGeneratedWireType.Fixed2",
        4 => "RpcGeneratedWireType.Fixed4",
        8 => "RpcGeneratedWireType.Fixed8",
        16 => "RpcGeneratedWireType.Fixed16",
        _ => throw new InvalidOperationException("Unsupported generated fixed size.")
    };

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string GetArrayCreationType(string elementType, string lengthExpression)
    {
        if (elementType.EndsWith("[]", StringComparison.Ordinal))
        {
            var firstRank = elementType.IndexOf("[]", StringComparison.Ordinal);
            return elementType.Substring(0, firstRank) + "[" + lengthExpression + "]" +
                   elementType.Substring(firstRank);
        }
        return elementType + "[" + lengthExpression + "]";
    }
}
