namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateClusterRouteManifest(ImmutableArray<ClusterRouteModel> routes)
    {
        var owner = string.Join("|", routes.Select(static route =>
            route.Cluster + ":" + route.AssemblyIdentity));
        var typeName = "__SharpLinkGeneratedClusterRouteManifest_" + Hashing.GetSha256(owner).Substring(0, 16);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        sb.AppendLine("[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public sealed class {typeName} : ISharpLinkGeneratedClusterRouteManifest");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly {typeName} Instance = new();");
        sb.AppendLine($"    public {typeName}() {{ }}");
        sb.AppendLine($"    public Assembly OwnerAssembly => typeof({typeName}).Assembly;");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedClusterAssemblyRoute> Routes => __routes;");
        sb.AppendLine("    private static readonly SharpLinkGeneratedClusterAssemblyRoute[] __routes = new SharpLinkGeneratedClusterAssemblyRoute[]");
        sb.AppendLine("    {");
        foreach (var route in routes)
        {
            sb.AppendLine("        new SharpLinkGeneratedClusterAssemblyRoute(");
            sb.AppendLine($"            new SharpLinkClusterKey(\"{EscapeString(route.Cluster)}\"),");
            sb.AppendLine($"            typeof({route.MarkerTypeName}).Assembly,");
            sb.AppendLine($"            \"{EscapeString(route.AssemblyIdentity)}\"),");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"internal static class {typeName}Initializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine($"        => SharpLinkGeneratedClusterRouteCatalog.Register({typeName}.Instance);");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
