namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateAssemblyManifest(
        ImmutableArray<RpcInterfaceModel?> interfaces,
        ImmutableArray<RpcServiceModel?> services,
        ImmutableArray<GeneratedCodecModel> codecs)
    {
        var contracts = interfaces
            .Where(static model => model is not null)
            .Select(static model => model!)
            .OrderBy(static model => model.Hash)
            .ToArray();
        var serviceModels = services
            .Where(static model => model is not null)
            .Select(static model => model!)
            .OrderBy(static model => model.Interface.Hash)
            .ThenBy(static model => model.ServiceFullName, StringComparer.Ordinal)
            .ToArray();
        if (contracts.Length == 0 && serviceModels.Length == 0 && codecs.IsDefaultOrEmpty)
            return string.Empty;

        var ownerType = contracts.Length != 0
            ? contracts[0].FullName
            : serviceModels.Length != 0 ? serviceModels[0].ServiceFullName : codecs[0].TypeName;
        var manifestTypeName = "__SharpLinkGeneratedAssemblyManifest_" +
            Hashing.GetSha256(ownerType).Substring(0, 16);
        var dependencies = serviceModels.SelectMany(static service => service.AssemblyDependencies)
            .Concat(contracts.SelectMany(static contract => contract.AssemblyDependencies))
            .Concat(codecs.SelectMany(static codec => codec.AssemblyDependencies))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static dependency => dependency, StringComparer.Ordinal)
            .ToArray();
        var compileTimeDescriptor = BuildCompileTimeDescriptor(contracts, serviceModels, codecs);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine("using SharpLink.Sdk;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: SharpLinkGeneratedAssemblyManifestAttribute(typeof(SharpLink.Generated.{manifestTypeName}))]");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        sb.AppendLine("[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public sealed class {manifestTypeName} : ISharpLinkGeneratedAssemblyManifest");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string CompileTimeDescriptor = \"{EscapeString(compileTimeDescriptor)}\";");
        sb.AppendLine($"    public static readonly {manifestTypeName} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"    public {manifestTypeName}() {{ }}");
        sb.AppendLine("    public int ApiVersion => SharpLinkGeneratedManifestVersions.Api;");
        sb.AppendLine("    public int ProtocolVersion => SharpLinkGeneratedManifestVersions.Protocol;");
        sb.AppendLine("    public string GeneratorVersion => \"0.8.2\";");
        sb.AppendLine($"    public Assembly OwnerAssembly => typeof({manifestTypeName}).Assembly;");
        sb.AppendLine("    string ISharpLinkGeneratedAssemblyManifest.CompileTimeDescriptor => CompileTimeDescriptor;");
        sb.AppendLine();
        AppendContractManifestArray(sb, contracts);
        AppendServiceManifestArray(sb, serviceModels);
        AppendCodecManifestArray(sb, codecs);
        sb.AppendLine("    private static readonly string[] __dependencies = new string[]");
        sb.AppendLine("    {");
        foreach (var dependency in dependencies)
            sb.AppendLine($"        \"{EscapeString(dependency)}\",");
        sb.AppendLine("    };");
        sb.AppendLine("    private static readonly IReadOnlyList<SharpLinkGeneratedContractDescriptor> __readOnlyContracts = Array.AsReadOnly(__contracts);");
        sb.AppendLine("    private static readonly IReadOnlyList<SharpLinkGeneratedServiceDescriptor> __readOnlyServices = Array.AsReadOnly(__services);");
        sb.AppendLine("    private static readonly IReadOnlyList<IRpcGeneratedCodecFactory> __readOnlyCodecs = Array.AsReadOnly(__codecs);");
        sb.AppendLine("    private static readonly IReadOnlyList<string> __readOnlyDependencies = Array.AsReadOnly(__dependencies);");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedContractDescriptor> Contracts => __readOnlyContracts;");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedServiceDescriptor> Services => __readOnlyServices;");
        sb.AppendLine("    public IReadOnlyList<IRpcGeneratedCodecFactory> Codecs => __readOnlyCodecs;");
        sb.AppendLine("    public IReadOnlyList<string> Dependencies => __readOnlyDependencies;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal static class __SharpLinkGeneratedAssemblyManifestInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine($"        => SharpLinkGeneratedAssemblyCatalog.Register({manifestTypeName}.Instance);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendContractManifestArray(StringBuilder sb, RpcInterfaceModel[] contracts)
    {
        sb.AppendLine("    private static readonly SharpLinkGeneratedContractDescriptor[] __contracts = new SharpLinkGeneratedContractDescriptor[]");
        sb.AppendLine("    {");
        foreach (var contract in contracts)
        {
            sb.AppendLine("        new SharpLinkGeneratedContractDescriptor(");
            sb.AppendLine($"            typeof({contract.FullName}),");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(contract.FullName))}\",");
            sb.AppendLine($"            {contract.Hash}L,");
            sb.AppendLine($"            \"{contract.Fingerprint}\",");
            sb.AppendLine("            Array.AsReadOnly(new SharpLinkGeneratedMethodDescriptor[]");
            sb.AppendLine("            {");
            foreach (var method in contract.Methods.OrderBy(static method => method.Hash))
            {
                sb.AppendLine("                new SharpLinkGeneratedMethodDescriptor(");
                sb.AppendLine($"                    \"{EscapeString(method.Name)}\",");
                sb.AppendLine($"                    {method.Hash}L,");
                sb.AppendLine($"                    RpcMethodKind.{GetMethodKind(method)},");
                sb.AppendLine($"                    {(method.HasCancellationToken || method.IsStreamReturn || method.Parameters.Any(static parameter => parameter.IsStream) ? "true" : "false")},");
                sb.AppendLine($"                    \"{EscapeString(method.RequestSchema)}\",");
                sb.AppendLine($"                    \"{EscapeString(method.ResponseSchema)}\",");
                sb.AppendLine($"                    \"{method.Fingerprint}\"),");
            }
            sb.AppendLine("            }),");
            sb.AppendLine($"            static channel => new {GetGeneratedContractTypeName(contract, "Proxy")}(channel),");
            sb.AppendLine($"            static () => new {GetGeneratedContractTypeName(contract, "Stub")}()),");
        }
        sb.AppendLine("    };");
    }

    private static void AppendServiceManifestArray(StringBuilder sb, RpcServiceModel[] services)
    {
        sb.AppendLine("    private static readonly SharpLinkGeneratedServiceDescriptor[] __services = new SharpLinkGeneratedServiceDescriptor[]");
        sb.AppendLine("    {");
        foreach (var service in services)
        {
            var dependencyTypes = string.Join(", ", service.ConstructorParameters.Select(static parameter => $"typeof({parameter.TypeName})"));
            var serviceFingerprint = Hashing.GetSha256(
                $"{service.ServiceFullName}|{service.Interface.Fingerprint}|{service.Lifetime}|" +
                string.Join("|", service.ConstructorParameters.Select(static parameter => parameter.TypeName)));
            var arguments = string.Join(", ", service.ConstructorParameters.Select(parameter =>
                $"({parameter.TypeName})(provider.GetService(typeof({parameter.TypeName})) ?? throw new InvalidOperationException(\"Required service dependency '{EscapeString(RemoveGlobalPrefix(parameter.TypeName))}' for '{EscapeString(RemoveGlobalPrefix(service.ServiceFullName))}' is not registered.\"))"));
            sb.AppendLine("        new SharpLinkGeneratedServiceDescriptor(");
            sb.AppendLine($"            typeof({service.Interface.FullName}),");
            sb.AppendLine($"            typeof({service.ServiceFullName}),");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(service.Interface.FullName))}\",");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(service.ServiceFullName))}\",");
            sb.AppendLine($"            {service.Interface.Hash}L,");
            sb.AppendLine($"            \"{serviceFingerprint}\",");
            sb.AppendLine($"            SharpLinkServiceLifetime.{service.Lifetime},");
            sb.AppendLine($"            Array.AsReadOnly(new Type[] {{ {dependencyTypes} }}),");
            sb.AppendLine($"            static provider => new {service.ServiceFullName}({arguments})),");
        }
        sb.AppendLine("    };");
    }

    private static void AppendCodecManifestArray(StringBuilder sb, ImmutableArray<GeneratedCodecModel> codecs)
    {
        sb.AppendLine("    private static readonly IRpcGeneratedCodecFactory[] __codecs = new IRpcGeneratedCodecFactory[]");
        sb.AppendLine("    {");
        foreach (var codec in codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            sb.AppendLine($"        new {codec.CodecName}.Factory(),");
        sb.AppendLine("    };");
    }

    private static string BuildCompileTimeDescriptor(
        RpcInterfaceModel[] contracts,
        RpcServiceModel[] services,
        ImmutableArray<GeneratedCodecModel> codecs)
    {
        var sb = new StringBuilder();
        foreach (var contract in contracts)
            sb.Append("C:").Append(contract.Hash).Append(':').Append(contract.FullName).Append(':').Append(contract.Fingerprint).Append(';');
        foreach (var service in services)
            sb.Append("S:").Append(service.Interface.Hash).Append(':').Append(service.ServiceFullName).Append(':').Append(service.Lifetime).Append(';');
        foreach (var codec in codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            sb.Append("D:").Append(codec.TypeName).Append(':').Append(codec.SchemaId).Append(';');
        return sb.ToString();
    }

    private static string GetGeneratedContractTypeName(RpcInterfaceModel contract, string suffix)
        => string.IsNullOrEmpty(contract.Namespace)
            ? $"global::{contract.Name}_{suffix}"
            : $"global::{contract.Namespace}.{contract.Name}_{suffix}";

    private static string RemoveGlobalPrefix(string value)
        => value.StartsWith("global::", StringComparison.Ordinal)
            ? value.Substring("global::".Length)
            : value;
}
