namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private const string GeneratedAbiIdentity = "sharplink-2.0-api4-rpcchannel-codec-provider-v3";
    private static string GenerateAssemblyManifest(
        ImmutableArray<RpcInterfaceModel?> interfaces,
        ImmutableArray<RpcServiceModel?> services,
        ImmutableArray<GeneratedCodecModel> codecs,
        ImmutableArray<GeneratedCodecModel> contractCodecs,
        ImmutableArray<GeneratedCodecHashModel> codecHashes)
    {
        var contracts = GetContractModels(interfaces);
        var serviceModels = GetServiceModels(services);
        if (contracts.Length == 0 && serviceModels.Length == 0 && codecs.IsDefaultOrEmpty && contractCodecs.IsDefaultOrEmpty)
            return string.Empty;

        var manifestTypeName = GetManifestTypeName(contracts, serviceModels, codecs, contractCodecs);
        var rpcIdentity = BuildRpcAssemblyIdentity(contracts, codecHashes);
        // Module dependencies come from generated artifacts and the finalized Codec graph. Contract
        // signature CLR references alone are not evidence that the referenced assembly publishes a
        // SharpLink generated manifest and therefore must not become dynamic-module dependencies.
        var dependencies = serviceModels.SelectMany(static service => service.AssemblyDependencies)
            .Concat(codecs.SelectMany(static codec => codec.AssemblyDependencies))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static dependency => dependency, StringComparer.Ordinal)
            .ToArray();
        var dependencySet = new HashSet<string>(dependencies, StringComparer.Ordinal);
        var contractDependencies = contractCodecs.SelectMany(static codec => codec.AssemblyDependencies)
            .Where(dependency => !dependencySet.Contains(dependency))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static dependency => dependency, StringComparer.Ordinal)
            .ToArray();
        var compileTimeDescriptor = BuildCompileTimeDescriptor(contracts, serviceModels, codecs, contractCodecs);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine("using SharpLink.Sdk;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: SharpLinkGeneratedAssemblyManifestAttribute(typeof(SharpLink.Generated.{manifestTypeName}), 4, 2, \"{EscapeString(ExecutingGeneratorVersion)}\", \"{GeneratedAbiIdentity}\")]");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        sb.AppendLine("[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public sealed partial class {manifestTypeName} : ISharpLinkGeneratedAssemblyManifest");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string CompileTimeDescriptor = \"{EscapeString(compileTimeDescriptor)}\";");
        sb.AppendLine($"    public static readonly {manifestTypeName} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"    public {manifestTypeName}() {{ }}");
        sb.AppendLine("    public static void Register()");
        sb.AppendLine("        => SharpLinkGeneratedAssemblyCatalog.Register(Instance);");
        sb.AppendLine("    public int ApiVersion => 4;");
        sb.AppendLine("    public int ProtocolVersion => 2;");
        sb.AppendLine($"    public string GeneratorVersion => \"{EscapeString(ExecutingGeneratorVersion)}\";");
        sb.AppendLine($"    public Assembly OwnerAssembly => typeof({manifestTypeName}).Assembly;");
        sb.AppendLine($"    public RpcHash128 RpcAssemblyHash => new RpcHash128({rpcIdentity.AssemblyHash.High.ToString(InvariantCulture)}UL, {rpcIdentity.AssemblyHash.Low.ToString(InvariantCulture)}UL);");
        sb.AppendLine("    string ISharpLinkGeneratedAssemblyManifest.CompileTimeDescriptor => CompileTimeDescriptor;");
        sb.AppendLine();
        AppendContractArtifactFactories(sb, contracts);
        AppendIdentifiedCodecFactory(sb);
        AppendContractManifestArray(sb, contracts);
        AppendServiceManifestArray(sb, serviceModels);
        AppendCodecManifestArray(sb, codecs);
        AppendContractCodecManifestArray(sb, contractCodecs);
        sb.AppendLine("    private static readonly string[] __dependencies = new string[]");
        sb.AppendLine("    {");
        foreach (var dependency in dependencies)
            sb.AppendLine($"        \"{EscapeString(dependency)}\",");
        sb.AppendLine("    };");
        sb.AppendLine("    private static readonly string[] __contractDependencies = new string[]");
        sb.AppendLine("    {");
        foreach (var dependency in contractDependencies)
            sb.AppendLine($"        \"{EscapeString(dependency)}\",");
        sb.AppendLine("    };");
        sb.AppendLine("    private static readonly IReadOnlyList<SharpLinkGeneratedContractDescriptor> __readOnlyContracts = Array.AsReadOnly(__contracts);");
        sb.AppendLine("    private static readonly IReadOnlyList<SharpLinkGeneratedServiceDescriptor> __readOnlyServices = Array.AsReadOnly(__services);");
        sb.AppendLine("    private static readonly IReadOnlyList<IRpcGeneratedCodecFactory> __readOnlyCodecs = Array.AsReadOnly(__codecs);");
        sb.AppendLine("    private static readonly IReadOnlyList<IRpcGeneratedCodecFactory> __readOnlyContractCodecs = Array.AsReadOnly(__contractCodecs);");
        sb.AppendLine("    private static readonly IReadOnlyList<string> __readOnlyDependencies = Array.AsReadOnly(__dependencies);");
        sb.AppendLine("    private static readonly IReadOnlyList<string> __readOnlyContractDependencies = Array.AsReadOnly(__contractDependencies);");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedContractDescriptor> Contracts => __readOnlyContracts;");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedServiceDescriptor> Services => __readOnlyServices;");
        sb.AppendLine("    public IReadOnlyList<IRpcGeneratedCodecFactory> Codecs => __readOnlyCodecs;");
        sb.AppendLine("    public IReadOnlyList<IRpcGeneratedCodecFactory> ContractCodecs => __readOnlyContractCodecs;");
        sb.AppendLine("    public IReadOnlyList<string> Dependencies => __readOnlyDependencies;");
        sb.AppendLine("    public IReadOnlyList<string> ContractDependencies => __readOnlyContractDependencies;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal static class __SharpLinkGeneratedAssemblyManifestInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine($"        => {manifestTypeName}.Register();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendContractArtifactFactories(StringBuilder sb, RpcInterfaceModel[] contracts)
    {
        foreach (var contract in contracts)
        {
            var identity = GetContractArtifactIdentity(contract);
            sb.AppendLine($"    private static object __CreateProxy_{identity}(IRpcChannel channel, IRpcCodecProvider codecs)");
            sb.AppendLine($"        => new __Proxy_{identity}(channel, codecs);");
            sb.AppendLine();
            sb.AppendLine($"    private static IRpcStub __CreateStub_{identity}(IRpcCodecProvider codecs)");
            sb.AppendLine($"        => new __Stub_{identity}(codecs);");
            sb.AppendLine();
        }
    }

    private static void AppendIdentifiedCodecFactory(StringBuilder sb)
    {
        sb.AppendLine("    private sealed class __SharpLinkIdentifiedCodecFactory : IRpcGeneratedCodecFactory");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IRpcGeneratedCodecFactory __inner;");
        sb.AppendLine();
        sb.AppendLine("        internal __SharpLinkIdentifiedCodecFactory(IRpcGeneratedCodecFactory inner, ulong hashHigh, ulong hashLow)");
        sb.AppendLine("        {");
        sb.AppendLine("            __inner = inner ?? throw new ArgumentNullException(nameof(inner));");
        sb.AppendLine("            CodecHash = new RpcHash128(hashHigh, hashLow);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public Type TargetType => __inner.TargetType;");
        sb.AppendLine("        public RpcHash128 CodecHash { get; }");
        sb.AppendLine("        public string SchemaId => __inner.SchemaId;");
        sb.AppendLine("        public string WireFormatId => __inner.WireFormatId;");
        sb.AppendLine("        public string? AdapterId => __inner.AdapterId;");
        sb.AppendLine("        public IRpcCodecAdapter? Adapter => __inner.Adapter;");
        sb.AppendLine("        public IRpcCodec Create(IRpcCodecProvider provider, IRpcCodecAdapterScope? adapterScope)");
        sb.AppendLine("            => __inner.Create(provider, adapterScope);");
        sb.AppendLine("        public bool IsCompatibleCodec(IRpcCodec codec) => __inner.IsCompatibleCodec(codec);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendContractManifestArray(StringBuilder sb, RpcInterfaceModel[] contracts)
    {
        sb.AppendLine("    private static readonly SharpLinkGeneratedContractDescriptor[] __contracts = new SharpLinkGeneratedContractDescriptor[]");
        sb.AppendLine("    {");
        foreach (var contract in contracts)
        {
            sb.AppendLine("        new SharpLinkGeneratedContractDescriptor(");
            sb.AppendLine($"            typeof({contract.FullName}),");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(contract.FullName))}\",");
            sb.AppendLine($"            {contract.Hash}L,");
            sb.AppendLine($"            \"{contract.Fingerprint}\",");
            sb.AppendLine("            Array.AsReadOnly(new SharpLinkGeneratedMethodDescriptor[]");
            sb.AppendLine("            {");
            foreach (var method in contract.Methods.OrderBy(static method => method.Hash))
            {
                sb.AppendLine("                new SharpLinkGeneratedMethodDescriptor(");
                sb.AppendLine($"                    \"{EscapeString(method.Name)}\",");
                sb.AppendLine($"                    {method.Hash}L,");
                sb.AppendLine($"                    RpcMethodKind.{GetMethodKind(method)},");
                sb.AppendLine($"                    {(method.HasCancellationToken || method.IsStreamReturn || method.Parameters.Any(static parameter => parameter.IsStream) ? "true" : "false")},");
                sb.AppendLine($"                    \"{EscapeString(method.RequestSchema)}\",");
                sb.AppendLine($"                    \"{EscapeString(method.ResponseSchema)}\",");
                sb.AppendLine($"                    \"{method.Fingerprint}\"),");
            }
            sb.AppendLine("            }),");
            sb.AppendLine($"            static (channel, codecs) => __CreateProxy_{GetContractArtifactIdentity(contract)}(channel, codecs),");
            sb.AppendLine($"            static codecs => __CreateStub_{GetContractArtifactIdentity(contract)}(codecs)),");
        }
        sb.AppendLine("    };");
    }

    private static void AppendServiceManifestArray(StringBuilder sb, RpcServiceModel[] services)
    {
        sb.AppendLine("    private static readonly SharpLinkGeneratedServiceDescriptor[] __services = new SharpLinkGeneratedServiceDescriptor[]");
        sb.AppendLine("    {");
        foreach (var service in services)
        {
            var dependencyTypes = string.Join(", ", service.ConstructorParameters.Select(static parameter => $"typeof({parameter.TypeName})"));
            var serviceFingerprint = Hashing.GetSha256(
                $"{service.ServiceFullName}|{service.Interface.Fingerprint}|{service.Lifetime}|" +
                string.Join("|", service.ConstructorParameters.Select(static parameter => parameter.TypeName)));
            var arguments = string.Join(", ", service.ConstructorParameters.Select(parameter =>
                $"({parameter.TypeName})(provider.GetService(typeof({parameter.TypeName})) ?? throw new InvalidOperationException(\"Required service dependency '{EscapeString(RemoveGlobalPrefix(parameter.TypeName))}' for '{EscapeString(RemoveGlobalPrefix(service.ServiceFullName))}' is not registered.\"))"));
            sb.AppendLine("        new SharpLinkGeneratedServiceDescriptor(");
            sb.AppendLine($"            typeof({service.Interface.FullName}),");
            sb.AppendLine($"            typeof({service.ServiceFullName}),");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(service.Interface.FullName))}\",");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(service.ServiceFullName))}\",");
            sb.AppendLine($"            {service.Interface.Hash}L,");
            sb.AppendLine($"            \"{serviceFingerprint}\",");
            sb.AppendLine($"            SharpLinkServiceLifetime.{service.Lifetime},");
            sb.AppendLine($"            Array.AsReadOnly(new Type[] {{ {dependencyTypes} }}),");
            sb.AppendLine($"            static provider => new {service.ServiceFullName}({arguments})),");
        }
        sb.AppendLine("    };");
    }

    private static void AppendCodecManifestArray(StringBuilder sb, ImmutableArray<GeneratedCodecModel> codecs)
    {
        sb.AppendLine("    private static readonly IRpcGeneratedCodecFactory[] __codecs = new IRpcGeneratedCodecFactory[]");
        sb.AppendLine("    {");
        foreach (var codec in codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            AppendIdentifiedCodecFactoryRegistration(sb, codec);
        sb.AppendLine("    };");
    }

    private static void AppendContractCodecManifestArray(
        StringBuilder sb,
        ImmutableArray<GeneratedCodecModel> codecs)
    {
        sb.AppendLine("    private static readonly IRpcGeneratedCodecFactory[] __contractCodecs = new IRpcGeneratedCodecFactory[]");
        sb.AppendLine("    {");
        foreach (var codec in codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            AppendIdentifiedCodecFactoryRegistration(sb, codec);
        sb.AppendLine("    };");
    }

    private static void AppendIdentifiedCodecFactoryRegistration(StringBuilder sb, GeneratedCodecModel codec)
        => sb.AppendLine(
            $"        new __SharpLinkIdentifiedCodecFactory(new {codec.CodecName}.Factory(), {codec.CodecHashHigh.ToString(InvariantCulture)}UL, {codec.CodecHashLow.ToString(InvariantCulture)}UL),");

    private static string BuildCompileTimeDescriptor(
        RpcInterfaceModel[] contracts,
        RpcServiceModel[] services,
        ImmutableArray<GeneratedCodecModel> codecs,
        ImmutableArray<GeneratedCodecModel> contractCodecs)
    {
        var sb = new StringBuilder();
        foreach (var contract in contracts)
            sb.Append("C:").Append(contract.Hash).Append(':').Append(contract.FullName).Append(':').Append(contract.Fingerprint).Append(';');
        foreach (var service in services)
            sb.Append("S:").Append(service.Interface.Hash).Append(':').Append(service.ServiceFullName).Append(':').Append(service.Lifetime).Append(';');
        foreach (var codec in codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            sb.Append("D:").Append(codec.TypeName).Append(':').Append(codec.SchemaId).Append(';');
        foreach (var codec in contractCodecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            sb.Append("K:").Append(codec.TypeName).Append(':').Append(codec.SchemaId).Append(';');
        return sb.ToString();
    }

    private static RpcInterfaceModel[] GetContractModels(ImmutableArray<RpcInterfaceModel?> interfaces)
        => interfaces
            .Where(static model => model is not null)
            .Select(static model => model!)
            .OrderBy(static model => model.Hash)
            .ToArray();

    private static RpcServiceModel[] GetServiceModels(ImmutableArray<RpcServiceModel?> services)
        => services
            .Where(static model => model is not null)
            .Select(static model => model!)
            .OrderBy(static model => model.Interface.Hash)
            .ThenBy(static model => model.ServiceFullName, StringComparer.Ordinal)
            .ToArray();

    private static string GetManifestTypeName(
        RpcInterfaceModel[] contracts,
        RpcServiceModel[] services,
        ImmutableArray<GeneratedCodecModel> codecs,
        ImmutableArray<GeneratedCodecModel> contractCodecs)
    {
        var ownerType = contracts.Length != 0
            ? contracts[0].FullName
            : services.Length != 0
                ? services[0].ServiceFullName
                : !codecs.IsDefaultOrEmpty
                    ? codecs[0].TypeName
                    : contractCodecs[0].TypeName;
        return "__SharpLinkGeneratedAssemblyManifest_" +
            Hashing.GetSha256(ownerType).Substring(0, 16);
    }

    private static string RemoveGlobalPrefix(string value)
        => value.StartsWith("global::", StringComparison.Ordinal)
            ? value.Substring("global::".Length)
            : value;
}
