namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateCodecs(
        ImmutableArray<GeneratedCodecModel> globalCodecs,
        ImmutableArray<GeneratedCodecModel> contractCodecs,
        DtoCodecAnalysisResult dtoAnalysis)
    {
        var codecs = globalCodecs.AddRange(contractCodecs);
        var emittedCodecs = codecs
            .GroupBy(static codec => codec.CodecName, StringComparer.Ordinal)
            .Select(static group => group.First())
            .ToImmutableArray();
        var dtoByCodecName = dtoAnalysis.Codecs
            .Concat(dtoAnalysis.ContractCodecs)
            .GroupBy(static codec => codec.CodecName, StringComparer.Ordinal)
            .ToDictionary(
                static group => group.Key,
                static group => group.First(),
                StringComparer.Ordinal);
        var globalConcreteCodecTypes = CreateConcreteCodecTypeMap(globalCodecs);
        var contractConcreteCodecTypes = CreateConcreteCodecTypeMap(globalCodecs, contractCodecs);
        var contractCodecNames = new HashSet<string>(
            contractCodecs.Select(static codec => codec.CodecName),
            StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        AppendAdapterCodecHolders(sb, emittedCodecs);

        if (emittedCodecs.Any(static codec =>
                codec.Kind == GeneratedCodecKind.Dto &&
                codec.Members.Any(static member => member.Kind == GeneratedMemberKind.String)))
            AppendGeneratedUtf16Helper(sb);

        foreach (var codec in emittedCodecs)
        {
            var concreteCodecTypes = contractCodecNames.Contains(codec.CodecName)
                ? contractConcreteCodecTypes
                : globalConcreteCodecTypes;
            if (codec.Kind == GeneratedCodecKind.Adapter)
                AppendAdapterCodecFactory(sb, codec);
            else if (codec.Kind == GeneratedCodecKind.Custom)
                AppendCustomCodecFactory(sb, codec);
            else if (codec.Kind == GeneratedCodecKind.Union)
                AppendUnionCodec(sb, codec, concreteCodecTypes);
            else if (codec.Kind == GeneratedCodecKind.Dto)
            {
                if (!dtoByCodecName.TryGetValue(codec.CodecName, out var dto))
                {
                    throw new InvalidOperationException(
                        $"DTO analysis result is missing emitter model '{codec.CodecName}'.");
                }
                AppendDtoCodec(sb, dto, concreteCodecTypes);
            }
            else
                AppendCollectionCodec(sb, codec, concreteCodecTypes);
        }

        return sb.ToString();
    }

    private static IReadOnlyDictionary<string, string> CreateConcreteCodecTypeMap(
        ImmutableArray<GeneratedCodecModel> codecs)
        => CreateConcreteCodecTypeMap(codecs, ImmutableArray<GeneratedCodecModel>.Empty);

    private static IReadOnlyDictionary<string, string> CreateConcreteCodecTypeMap(
        ImmutableArray<GeneratedCodecModel> codecs,
        ImmutableArray<GeneratedCodecModel> overrides)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var codec in codecs)
            Apply(codec);
        foreach (var codec in overrides)
            Apply(codec);
        return result;

        void Apply(GeneratedCodecModel codec)
        {
            var concreteType = GetConcreteCodecType(codec);
            if (concreteType is null)
                result.Remove(codec.TypeName);
            else
                result[codec.TypeName] = concreteType;
        }
    }

    private static string? GetConcreteCodecType(GeneratedCodecModel codec)
        => codec.Kind switch
        {
            GeneratedCodecKind.Custom when codec.CustomCodecSupportsConcreteDispatch => codec.CustomCodecType,
            GeneratedCodecKind.Custom or GeneratedCodecKind.Adapter => null,
            GeneratedCodecKind.Dto or
            GeneratedCodecKind.Union or
            GeneratedCodecKind.Array or
            GeneratedCodecKind.List or
            GeneratedCodecKind.Dictionary or
            GeneratedCodecKind.Memory or
            GeneratedCodecKind.ReadOnlyMemory or
            GeneratedCodecKind.ImmutableArray or
            GeneratedCodecKind.Nullable => $"global::SharpLink.Generated.{codec.CodecName}",
            _ => null
        };

    private static string GetCodecStorageType(
        string payloadType,
        string codecLookupType,
        IReadOnlyDictionary<string, string> concreteCodecTypes)
        => concreteCodecTypes.TryGetValue(codecLookupType, out var concreteType)
            ? concreteType
            : $"IRpcCodec<{payloadType}>";

    private static string GetCodecResolveExpression(
        string providerExpression,
        string payloadType,
        string codecLookupType,
        IReadOnlyDictionary<string, string> concreteCodecTypes)
        => concreteCodecTypes.TryGetValue(codecLookupType, out var concreteType)
            ? $"({concreteType}){providerExpression}.GetCodec<{codecLookupType}>()"
            : $"{providerExpression}.GetCodec<{payloadType}>()";

    private static bool TryGetStaticGeneratedCodecCoreType(
        string codecLookupType,
        IReadOnlyDictionary<string, string> concreteCodecTypes,
        out string coreType)
    {
        if (concreteCodecTypes.TryGetValue(codecLookupType, out var concreteType) &&
            concreteType.StartsWith("global::SharpLink.Generated.", StringComparison.Ordinal))
        {
            coreType = concreteType + ".Core";
            return true;
        }

        coreType = string.Empty;
        return false;
    }

    private static string GetCodecHotStorageType(
        string payloadType,
        string codecLookupType,
        IReadOnlyDictionary<string, string> concreteCodecTypes)
        => TryGetStaticGeneratedCodecCoreType(codecLookupType, concreteCodecTypes, out var coreType)
            ? coreType
            : $"IRpcCodec<{payloadType}>";

    private static string GetCodecHotResolveExpression(
        string providerExpression,
        string payloadType,
        string codecLookupType,
        IReadOnlyDictionary<string, string> concreteCodecTypes)
    {
        if (!TryGetStaticGeneratedCodecCoreType(codecLookupType, concreteCodecTypes, out _))
            return $"{providerExpression}.GetCodec<{payloadType}>()";

        var resolved = GetCodecResolveExpression(
            providerExpression,
            payloadType,
            codecLookupType,
            concreteCodecTypes);
        return $"({resolved}).StaticCore";
    }

    private static string GetCodecHotBoundExpression(
        string boundExpression,
        string codecLookupType,
        IReadOnlyDictionary<string, string> concreteCodecTypes)
        => TryGetStaticGeneratedCodecCoreType(codecLookupType, concreteCodecTypes, out _)
            ? $"{boundExpression}.StaticCore"
            : boundExpression;

    private static string GetWireType(int fixedSize) => fixedSize switch
    {
        1 => "RpcGeneratedWireType.Fixed1",
        2 => "RpcGeneratedWireType.Fixed2",
        4 => "RpcGeneratedWireType.Fixed4",
        8 => "RpcGeneratedWireType.Fixed8",
        16 => "RpcGeneratedWireType.Fixed16",
        _ => throw new InvalidOperationException("Unsupported generated fixed size.")
    };

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string? GetSemanticFixedMethod(string typeName)
        => typeName.Replace("global::", string.Empty) switch
        {
            "System.Text.Rune" => "Rune",
            "decimal" or "System.Decimal" => "Decimal",
            "System.DateOnly" => "DateOnly",
            "System.DateTime" => "DateTime",
            "System.TimeOnly" => "TimeOnly",
            "System.DateTimeOffset" => "DateTimeOffset",
            _ => null
        };
}
