namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateProxy(RpcInterfaceModel model)
    {
        var nsDeclaration = string.IsNullOrEmpty(model.Namespace) ? "" : $"namespace {model.Namespace};";
        var sb = new StringBuilder();
        sb.AppendLine($$"""
                        // <auto-generated/>
                        #nullable enable
                        using SharpLink.Abstractions;
                        using SharpLink.Runtime;
                        using System;
                        using System.Buffers;
                        using System.Buffers.Binary;
                        using System.Collections.Generic;
                        using System.IO;
                        using System.Runtime.CompilerServices;
                        using System.Threading;
                        using System.Threading.Tasks;

                        {{nsDeclaration}}

                        public sealed class {{model.Name}}_Proxy : {{model.FullName}}
                        {
                            private readonly IRpcChannel _channel;
                        """);

        foreach (var method in model.Methods)
            AppendProxyFields(sb, model, method);

        sb.AppendLine($"    public {model.Name}_Proxy(IRpcChannel channel)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(channel);");
        sb.AppendLine("        _channel = channel;");
        foreach (var method in model.Methods)
        {
            var suffix = GetMethodSuffix(method);
            var payloadParameters = GetPayloadParameters(method);
            if (payloadParameters.Length != 0)
                sb.AppendLine($"        __requestCodec_{suffix} = new {GetRequestCodecType(model, method)}(channel.RuntimeContext.Codecs);");
            if (!method.IsOneWay)
                sb.AppendLine($"        __responseCodec_{suffix} = channel.RuntimeContext.Codecs.GetCodec<{GetResponseType(method)}>();");
        }
        sb.AppendLine("    }");

        foreach (var method in model.Methods)
            AppendProxyMethod(sb, model, method);

        sb.AppendLine("}");

        foreach (var method in model.Methods)
        {
            if (GetPayloadParameters(method).Length != 0)
                AppendGeneratedRequest(sb, model, method);
            if (GetStreamParameters(method).Length != 0)
                AppendGeneratedStreams(sb, model, method);
        }

        sb.AppendLine($$"""

                        internal static class {{model.Name}}_ProxyRegistration
                        {
                            [ModuleInitializer]
                            internal static void Register()
                            {
                                SharpLink.Abstractions.GeneratedProxyRegistry.Register(typeof({{model.FullName}}), static channel => new {{model.Name}}_Proxy(channel));
                            }
                        }
                        """);
        return sb.ToString();
    }

    private static void AppendProxyFields(StringBuilder sb, RpcInterfaceModel model, RpcMethodModel method)
    {
        var suffix = GetMethodSuffix(method);
        var kind = GetMethodKind(method);
        var hasPayloadResponse = !method.IsOneWay && !method.IsVoid;
        var hasClientStreams = GetStreamParameters(method).Length != 0;
        var methodTimeout = method.TimeoutSeconds is { } seconds
            ? $"TimeSpan.FromSeconds({seconds.ToString("R", InvariantCulture)}d)"
            : "null";
        sb.AppendLine(
            $"    private static readonly RpcMethodDescriptor __method_{suffix} = new({model.Hash}L, {method.Hash}L, RpcMethodKind.{kind}, {(hasPayloadResponse ? "true" : "false")}, {(hasClientStreams ? "true" : "false")}, {(method.HasTimeoutAttribute ? "true" : "false")}, {methodTimeout}, {(method.IsIdempotent ? "true" : "false")});");

        if (GetPayloadParameters(method).Length != 0)
            sb.AppendLine($"    private readonly IRpcCodec<{GetRequestType(model, method)}> __requestCodec_{suffix};");
        if (!method.IsOneWay)
            sb.AppendLine($"    private readonly IRpcCodec<{GetResponseType(method)}> __responseCodec_{suffix};");
    }

    private static void AppendProxyMethod(StringBuilder sb, RpcInterfaceModel model, RpcMethodModel method)
    {
        var suffix = GetMethodSuffix(method);
        var parameterList = string.Join(", ", method.Parameters.Select(static parameter => $"{parameter.Type} {parameter.Name}"));
        var payloadParameters = GetPayloadParameters(method);
        var streamParameters = GetStreamParameters(method);
        var requestType = payloadParameters.Length == 0 ? "RpcEmptyRequest" : GetRequestType(model, method);
        var requestCodec = payloadParameters.Length == 0 ? "RpcEmptyRequestCodec.Instance" : $"__requestCodec_{suffix}";
        var requestValue = payloadParameters.Length == 0
            ? "default(RpcEmptyRequest)"
            : $"new {requestType}({string.Join(", ", payloadParameters.Select(static parameter => parameter.Name))})";
        var streamsType = streamParameters.Length == 0 ? "RpcNoClientStreams" : GetStreamsType(model, method);
        var streamsValue = streamParameters.Length == 0
            ? "default(RpcNoClientStreams)"
            : $"new {streamsType}({string.Join(", ", streamParameters.Select(static parameter => parameter.Name))})";
        var cancellationToken = method.Parameters.FirstOrDefault(static parameter => parameter.IsCancellationToken)?.Name ?? "default";
        var options = method.Parameters.FirstOrDefault(static parameter => parameter.IsCallOptions)?.Name ?? "default";

        sb.AppendLine($"    public {method.ReturnType} {method.Name}({parameterList})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __request = {requestValue};");
        if (streamParameters.Length != 0 || method.IsOneWay)
            sb.AppendLine($"        var __streams = {streamsValue};");

        string invocation;
        if (method.IsStreamReturn)
        {
            invocation = streamParameters.Length == 0
                ? $"_channel.InvokeServerStreamingAsync(__method_{suffix}, in __request, {requestCodec}, __responseCodec_{suffix}, {options}, {cancellationToken})"
                : $"_channel.InvokeDuplexStreamingAsync(__method_{suffix}, in __request, {requestCodec}, __responseCodec_{suffix}, in __streams, {options}, {cancellationToken})";
            sb.AppendLine($"        return {invocation};");
        }
        else if (method.IsOneWay)
        {
            invocation = $"_channel.InvokeOneWayAsync(__method_{suffix}, in __request, {requestCodec}, in __streams, {options}, {cancellationToken})";
            AppendTaskLikeReturn(sb, method, invocation, hasResult: false);
        }
        else if (streamParameters.Length != 0)
        {
            invocation = $"_channel.InvokeClientStreamingAsync(__method_{suffix}, in __request, {requestCodec}, __responseCodec_{suffix}, in __streams, {options}, {cancellationToken})";
            AppendTaskLikeReturn(sb, method, invocation, hasResult: !method.IsVoid);
        }
        else
        {
            invocation = $"_channel.InvokeUnaryAsync(__method_{suffix}, in __request, {requestCodec}, __responseCodec_{suffix}, {options}, {cancellationToken})";
            AppendTaskLikeReturn(sb, method, invocation, hasResult: !method.IsVoid);
        }

        sb.AppendLine("    }");
    }

    private static void AppendTaskLikeReturn(
        StringBuilder sb,
        RpcMethodModel method,
        string invocation,
        bool hasResult)
    {
        var returnsValueTask = method.ReturnType.Contains("ValueTask");
        if (hasResult)
        {
            sb.AppendLine(returnsValueTask
                ? $"        return {invocation};"
                : $"        return {invocation}.AsTask();");
            return;
        }

        // Response-less non-one-way methods use byte as an internal acknowledgement type.
        if (!method.IsOneWay)
            invocation += ".AsVoid()";
        sb.AppendLine(returnsValueTask
            ? $"        return {invocation};"
            : $"        return {invocation}.AsTask();");
    }

    private static void AppendGeneratedRequest(StringBuilder sb, RpcInterfaceModel model, RpcMethodModel method)
    {
        var requestType = GetRequestType(model, method);
        var codecType = GetRequestCodecType(model, method);
        var parameters = GetPayloadParameters(method);
        var blittable = parameters.Where(static parameter => parameter.IsBlittable).ToArray();
        var complex = parameters.Where(static parameter => !parameter.IsBlittable).ToArray();

        sb.AppendLine($"internal readonly struct {requestType}");
        sb.AppendLine("{");
        foreach (var parameter in parameters)
            sb.AppendLine($"    internal readonly {parameter.Type} {parameter.Name};");
        sb.AppendLine($"    internal {requestType}({string.Join(", ", parameters.Select(static parameter => $"{parameter.Type} {parameter.Name}"))})");
        sb.AppendLine("    {");
        foreach (var parameter in parameters)
            sb.AppendLine($"        this.{parameter.Name} = {parameter.Name};");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        sb.AppendLine($"internal sealed class {codecType} : IRpcCodec<{requestType}>");
        sb.AppendLine("{");
        foreach (var parameter in complex)
            sb.AppendLine($"    private readonly IRpcCodec<{parameter.Type}> __codec_{parameter.Name};");
        sb.AppendLine($"    internal {codecType}(IRpcCodecProvider codecs)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(codecs);");
        foreach (var parameter in complex)
            sb.AppendLine($"        __codec_{parameter.Name} = codecs.GetCodec<{parameter.Type}>();");
        sb.AppendLine("    }");

        sb.AppendLine($"    public void Serialize(in {requestType} value, IBufferWriter<byte> writer)");
        sb.AppendLine("    {");
        if (blittable.Length != 0)
        {
            var total = string.Join(" + ", blittable.Select(parameter => GetInlineSizeToken(parameter.Type)));
            sb.AppendLine($"        var fixedSize = {total};");
            sb.AppendLine("        var fixedSpan = writer.GetSpan(fixedSize);");
            sb.AppendLine("        var fixedOffset = 0;");
            foreach (var parameter in blittable)
            {
                var size = GetInlineSizeToken(parameter.Type);
                sb.AppendLine($"        Unsafe.WriteUnaligned(ref System.Runtime.InteropServices.MemoryMarshal.GetReference(fixedSpan.Slice(fixedOffset, {size})), value.{parameter.Name});");
                sb.AppendLine($"        fixedOffset += {size};");
            }
            sb.AppendLine("        writer.Advance(fixedSize);");
        }
        if (complex.Length != 0)
            sb.AppendLine("        var rpcWriter = writer as IRpcByteBufferWriter ?? throw new InvalidOperationException(\"Generated request codecs require the SharpLink packet writer.\");");
        for (var index = 0; index < complex.Length; index++)
        {
            var parameter = complex[index];
            sb.AppendLine($"        var lengthOffset_{index} = rpcWriter.WrittenCount;");
            sb.AppendLine("        writer.Advance(sizeof(int));");
            sb.AppendLine($"        var start_{index} = rpcWriter.WrittenCount;");
            sb.AppendLine($"        __codec_{parameter.Name}.Serialize(value.{parameter.Name}, writer);");
            sb.AppendLine($"        var length_{index} = rpcWriter.WrittenCount - start_{index};");
            sb.AppendLine($"        var written_{index} = rpcWriter.WrittenSpan;");
            sb.AppendLine($"        BinaryPrimitives.WriteInt32LittleEndian(written_{index}.Slice(lengthOffset_{index}, sizeof(int)), length_{index});");
        }
        sb.AppendLine("    }");

        sb.AppendLine($"    public {requestType} Deserialize(in ReadOnlySequence<byte> payload)");
        sb.AppendLine("    {");
        sb.AppendLine("        var reader = new SequenceReader<byte>(payload);");
        foreach (var parameter in blittable)
        {
            var size = GetInlineSizeToken(parameter.Type);
            sb.AppendLine($"        if (reader.Remaining < {size}) throw new InvalidDataException(\"Request field '{parameter.Name}' is truncated.\");");
            sb.AppendLine($"        {parameter.Type} value_{parameter.Name};");
            sb.AppendLine($"        if (reader.UnreadSpan.Length >= {size})");
            sb.AppendLine($"            value_{parameter.Name} = Unsafe.ReadUnaligned<{parameter.Type}>(in System.Runtime.InteropServices.MemoryMarshal.GetReference(reader.UnreadSpan));");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine($"            Span<byte> temporary_{parameter.Name} = stackalloc byte[{size}];");
            sb.AppendLine($"            if (!reader.TryCopyTo(temporary_{parameter.Name})) throw new InvalidDataException(\"Request field is truncated.\");");
            sb.AppendLine($"            value_{parameter.Name} = Unsafe.ReadUnaligned<{parameter.Type}>(in System.Runtime.InteropServices.MemoryMarshal.GetReference(temporary_{parameter.Name}));");
            sb.AppendLine("        }");
            sb.AppendLine($"        reader.Advance({size});");
        }
        foreach (var parameter in complex)
        {
            sb.AppendLine($"        if (!reader.TryReadLittleEndian(out int length_{parameter.Name}) || length_{parameter.Name} < 0 || reader.Remaining < length_{parameter.Name})");
            sb.AppendLine($"            throw new InvalidDataException(\"Request field '{parameter.Name}' has an invalid length.\");");
            sb.AppendLine($"        var payload_{parameter.Name} = reader.UnreadSequence.Slice(0, length_{parameter.Name});");
            var nullGuard = parameter.IsValueType || parameter.IsNullableReference
                ? ""
                : $" ?? throw new InvalidDataException(\"Request field '{parameter.Name}' is null.\")";
            sb.AppendLine($"        var value_{parameter.Name} = __codec_{parameter.Name}.Deserialize(payload_{parameter.Name}){nullGuard};");
            sb.AppendLine($"        reader.Advance(length_{parameter.Name});");
        }
        sb.AppendLine("        if (reader.Remaining != 0) throw new InvalidDataException(\"Request contains trailing data.\");");
        sb.AppendLine($"        return new {requestType}({string.Join(", ", parameters.Select(static parameter => $"value_{parameter.Name}"))});");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void AppendGeneratedStreams(StringBuilder sb, RpcInterfaceModel model, RpcMethodModel method)
    {
        var streamsType = GetStreamsType(model, method);
        var streams = GetStreamParameters(method);
        sb.AppendLine($"internal readonly struct {streamsType} : IRpcClientStreamWriter");
        sb.AppendLine("{");
        foreach (var stream in streams)
            sb.AppendLine($"    private readonly {stream.Type} _{stream.Name};");
        sb.AppendLine($"    internal {streamsType}({string.Join(", ", streams.Select(static stream => $"{stream.Type} {stream.Name}"))})");
        sb.AppendLine("    {");
        foreach (var stream in streams)
            sb.AppendLine($"        _{stream.Name} = {stream.Name};");
        sb.AppendLine("    }");

        if (streams.Length == 1)
        {
            var stream = streams[0];
            sb.AppendLine("    public ValueTask WriteAsync(IRpcClientStreamSink sink, long requestId, CancellationToken cancellationToken)");
            sb.AppendLine($"        => new(sink.SendClientStreamAsync(requestId, (ushort)1, _{stream.Name}, cancellationToken));");
        }
        else
        {
            sb.AppendLine("    public async ValueTask WriteAsync(IRpcClientStreamSink sink, long requestId, CancellationToken cancellationToken)");
            sb.AppendLine("    {");
            for (var index = 0; index < streams.Length; index++)
                sb.AppendLine($"        var pending_{index} = sink.SendClientStreamAsync(requestId, (ushort){index + 1}, _{streams[index].Name}, cancellationToken);");
            for (var index = 0; index < streams.Length; index++)
                sb.AppendLine($"        await pending_{index}.ConfigureAwait(false);");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
    }

    private static RpcParameterModel[] GetPayloadParameters(RpcMethodModel method)
        => method.Parameters
            .Where(static parameter => !parameter.IsStream && !parameter.IsCancellationToken && !parameter.IsCallOptions)
            .ToArray();

    private static RpcParameterModel[] GetStreamParameters(RpcMethodModel method)
        => method.Parameters.Where(static parameter => parameter.IsStream).ToArray();

    private static string GetResponseType(RpcMethodModel method)
        => method.IsStreamReturn ? method.StreamItemType! : method.IsVoid ? "byte" : method.GenericArgumentType!;

    private static string GetMethodKind(RpcMethodModel method)
    {
        var hasStreams = GetStreamParameters(method).Length != 0;
        if (method.IsStreamReturn)
            return hasStreams ? "DuplexStreaming" : "ServerStreaming";
        if (method.IsOneWay)
            return "OneWay";
        return hasStreams ? "ClientStreaming" : "Unary";
    }

    private static string GetMethodSuffix(RpcMethodModel method)
        => unchecked((ulong)method.Hash).ToString("X16", InvariantCulture);

    private static string GetRequestType(RpcInterfaceModel model, RpcMethodModel method)
        => $"__{model.Name}_SharpLinkRequest_{GetMethodSuffix(method)}";

    private static string GetRequestCodecType(RpcInterfaceModel model, RpcMethodModel method)
        => $"__{model.Name}_SharpLinkRequestCodec_{GetMethodSuffix(method)}";

    private static string GetStreamsType(RpcInterfaceModel model, RpcMethodModel method)
        => $"__{model.Name}_SharpLinkStreams_{GetMethodSuffix(method)}";

    private static string GetInlineSizeToken(string typeName)
        => TryGetConstantSize(typeName, out var size)
            ? size.ToString(InvariantCulture)
            : GetSizeExpression(typeName);
}
