namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateAssemblyManifest(
        ImmutableArray<RpcInterfaceModel?> interfaces,
        ImmutableArray<RpcServiceModel?> services,
        ImmutableArray<GeneratedCodecModel> codecs,
        ImmutableArray<GeneratedCodecModel> contractCodecs,
        ImmutableArray<GeneratedContractCodecPolicy> contractPolicies)
    {
        var contracts = interfaces
            .Where(static model => model is not null)
            .Select(static model => model!)
            .OrderBy(static model => model.Hash)
            .ToArray();
        var serviceModels = services
            .Where(static model => model is not null)
            .Select(static model => model!)
            .OrderBy(static model => model.Interface.Hash)
            .ThenBy(static model => model.ServiceFullName, StringComparer.Ordinal)
            .ToArray();
        if (contracts.Length == 0 && serviceModels.Length == 0 && codecs.IsDefaultOrEmpty &&
            contractCodecs.IsDefaultOrEmpty)
        {
            // Contract policies only describe emitted Contract artifacts. Invalid/suppressed
            // Contracts may still leave analysis policy records behind, but those records must
            // not force an otherwise empty assembly manifest or become its synthetic owner.
            return string.Empty;
        }

        var ownerType = contracts.Length != 0
            ? contracts[0].FullName
            : serviceModels.Length != 0
                ? serviceModels[0].ServiceFullName
                : !codecs.IsDefaultOrEmpty ? codecs[0].TypeName : contractCodecs[0].TypeName;
        var manifestTypeName = "__SharpLinkGeneratedAssemblyManifest_" +
            Hashing.GetSha256(ownerType).Substring(0, 16);

        // Assembly Dependencies now describe only artifacts that remain visible when Contracts are
        // hidden (services + global/default Codecs). Contract-only dependency closure travels with
        // each SharpLinkGeneratedContractCodecSet instead of leaking through dependency views.
        var dependencies = serviceModels.SelectMany(static service => service.AssemblyDependencies)
            .Concat(codecs.SelectMany(static codec => codec.AssemblyDependencies))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static dependency => dependency, StringComparer.Ordinal)
            .ToArray();
        var compileTimeDescriptor = BuildCompileTimeDescriptor(
            contracts,
            serviceModels,
            codecs,
            contractPolicies);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine("using SharpLink.Sdk;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: SharpLinkGeneratedAssemblyManifestAttribute(typeof(SharpLink.Generated.{manifestTypeName}))]");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        sb.AppendLine("[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public sealed class {manifestTypeName} : ISharpLinkGeneratedAssemblyManifest");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string CompileTimeDescriptor = \"{EscapeString(compileTimeDescriptor)}\";");
        sb.AppendLine($"    public static readonly {manifestTypeName} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"    public {manifestTypeName}() {{ }}");
        sb.AppendLine("    public static void Register()");
        sb.AppendLine("        => SharpLinkGeneratedAssemblyCatalog.Register(Instance);");
        sb.AppendLine("    public int ApiVersion => SharpLinkGeneratedManifestVersions.Api;");
        sb.AppendLine("    public int ProtocolVersion => SharpLinkGeneratedManifestVersions.Protocol;");
        sb.AppendLine($"    public string GeneratorVersion => \"{EscapeString(ExecutingGeneratorVersion)}\";");
        sb.AppendLine($"    public Assembly OwnerAssembly => typeof({manifestTypeName}).Assembly;");
        sb.AppendLine("    string ISharpLinkGeneratedAssemblyManifest.CompileTimeDescriptor => CompileTimeDescriptor;");
        sb.AppendLine();
        AppendContractManifestArray(sb, contracts);
        AppendServiceManifestArray(sb, serviceModels);
        AppendCodecManifestArray(sb, codecs);
        AppendContractCodecManifestArray(sb);
        AppendContractCodecSetArray(sb, contracts, contractPolicies);
        sb.AppendLine("    private static readonly string[] __dependencies = new string[]");
        sb.AppendLine("    {");
        foreach (var dependency in dependencies)
            sb.AppendLine($"        \"{EscapeString(dependency)}\",");
        sb.AppendLine("    };");
        sb.AppendLine("    private static readonly IReadOnlyList<SharpLinkGeneratedContractDescriptor> __readOnlyContracts = Array.AsReadOnly(__contracts);");
        sb.AppendLine("    private static readonly IReadOnlyList<SharpLinkGeneratedServiceDescriptor> __readOnlyServices = Array.AsReadOnly(__services);");
        sb.AppendLine("    private static readonly IReadOnlyList<IRpcGeneratedCodecFactory> __readOnlyCodecs = Array.AsReadOnly(__codecs);");
        sb.AppendLine("    private static readonly IReadOnlyList<IRpcGeneratedCodecFactory> __readOnlyContractCodecs = Array.AsReadOnly(__contractCodecs);");
        sb.AppendLine("    private static readonly IReadOnlyList<SharpLinkGeneratedContractCodecSet> __readOnlyContractCodecSets = Array.AsReadOnly(__contractCodecSets);");
        sb.AppendLine("    private static readonly IReadOnlyList<string> __readOnlyDependencies = Array.AsReadOnly(__dependencies);");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedContractDescriptor> Contracts => __readOnlyContracts;");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedServiceDescriptor> Services => __readOnlyServices;");
        sb.AppendLine("    public IReadOnlyList<IRpcGeneratedCodecFactory> Codecs => __readOnlyCodecs;");
        sb.AppendLine("    public IReadOnlyList<IRpcGeneratedCodecFactory> ContractCodecs => __readOnlyContractCodecs;");
        sb.AppendLine("    public IReadOnlyList<SharpLinkGeneratedContractCodecSet> ContractCodecSets => __readOnlyContractCodecSets;");
        sb.AppendLine("    public IReadOnlyList<string> Dependencies => __readOnlyDependencies;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal static class __SharpLinkGeneratedAssemblyManifestInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine($"        => {manifestTypeName}.Register();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendContractManifestArray(StringBuilder sb, RpcInterfaceModel[] contracts)
    {
        sb.AppendLine("    private static readonly SharpLinkGeneratedContractDescriptor[] __contracts = new SharpLinkGeneratedContractDescriptor[]");
        sb.AppendLine("    {");
        foreach (var contract in contracts)
        {
            sb.AppendLine("        new SharpLinkGeneratedContractDescriptor(");
            sb.AppendLine($"            typeof({contract.FullName}),");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(contract.FullName))}\",");
            sb.AppendLine($"            {contract.Hash}L,");
            sb.AppendLine($"            \"{contract.Fingerprint}\",");
            sb.AppendLine("            Array.AsReadOnly(new SharpLinkGeneratedMethodDescriptor[]");
            sb.AppendLine("            {");
            foreach (var method in contract.Methods.OrderBy(static method => method.Hash))
            {
                sb.AppendLine("                new SharpLinkGeneratedMethodDescriptor(");
                sb.AppendLine($"                    \"{EscapeString(method.Name)}\",");
                sb.AppendLine($"                    {method.Hash}L,");
                sb.AppendLine($"                    RpcMethodKind.{GetMethodKind(method)},");
                sb.AppendLine($"                    {(method.HasCancellationToken || method.IsStreamReturn || method.Parameters.Any(static parameter => parameter.IsStream) ? "true" : "false")},");
                sb.AppendLine($"                    \"{EscapeString(method.RequestSchema)}\",");
                sb.AppendLine($"                    \"{EscapeString(method.ResponseSchema)}\",");
                sb.AppendLine($"                    \"{method.Fingerprint}\"),");
            }
            sb.AppendLine("            }),");
            sb.AppendLine($"            static (channel, codecs) => new {GetGeneratedContractTypeName(contract, "Proxy")}(channel, codecs),");
            sb.AppendLine($"            static codecs => new {GetGeneratedContractTypeName(contract, "Stub")}(codecs)),");
        }
        sb.AppendLine("    };");
    }

    private static void AppendServiceManifestArray(StringBuilder sb, RpcServiceModel[] services)
    {
        sb.AppendLine("    private static readonly SharpLinkGeneratedServiceDescriptor[] __services = new SharpLinkGeneratedServiceDescriptor[]");
        sb.AppendLine("    {");
        foreach (var service in services)
        {
            var dependencyTypes = string.Join(", ", service.ConstructorParameters.Select(static parameter => $"typeof({parameter.TypeName})"));
            var serviceFingerprint = Hashing.GetSha256(
                $"{service.ServiceFullName}|{service.Interface.Fingerprint}|{service.Lifetime}|" +
                string.Join("|", service.ConstructorParameters.Select(static parameter => parameter.TypeName)));
            var arguments = string.Join(", ", service.ConstructorParameters.Select(parameter =>
                $"({parameter.TypeName})(provider.GetService(typeof({parameter.TypeName})) ?? throw new InvalidOperationException(\"Required service dependency '{EscapeString(RemoveGlobalPrefix(parameter.TypeName))}' for '{EscapeString(RemoveGlobalPrefix(service.ServiceFullName))}' is not registered.\"))"));
            sb.AppendLine("        new SharpLinkGeneratedServiceDescriptor(");
            sb.AppendLine($"            typeof({service.Interface.FullName}),");
            sb.AppendLine($"            typeof({service.ServiceFullName}),");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(service.Interface.FullName))}\",");
            sb.AppendLine($"            \"{EscapeString(RemoveGlobalPrefix(service.ServiceFullName))}\",");
            sb.AppendLine($"            {service.Interface.Hash}L,");
            sb.AppendLine($"            \"{serviceFingerprint}\",");
            sb.AppendLine($"            SharpLinkServiceLifetime.{service.Lifetime},");
            sb.AppendLine($"            Array.AsReadOnly(new Type[] {{ {dependencyTypes} }}),");
            sb.AppendLine($"            static provider => new {service.ServiceFullName}({arguments})),");
        }
        sb.AppendLine("    };");
    }

    private static void AppendCodecManifestArray(StringBuilder sb, ImmutableArray<GeneratedCodecModel> codecs)
    {
        sb.AppendLine("    private static readonly IRpcGeneratedCodecFactory[] __codecs = new IRpcGeneratedCodecFactory[]");
        sb.AppendLine("    {");
        foreach (var codec in codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            sb.AppendLine($"        new {codec.CodecName}.Factory(),");
        sb.AppendLine("    };");
    }

    private static void AppendContractCodecManifestArray(StringBuilder sb)
    {
        // API 5 moves Contract policy out of this assembly-wide table. Keep the member for custom
        // manifest compatibility, but generated manifests intentionally leave it empty.
        sb.AppendLine("    private static readonly IRpcGeneratedCodecFactory[] __contractCodecs = Array.Empty<IRpcGeneratedCodecFactory>();");
    }

    private static void AppendContractCodecSetArray(
        StringBuilder sb,
        RpcInterfaceModel[] contracts,
        ImmutableArray<GeneratedContractCodecPolicy> contractPolicies)
    {
        var policyByContract = contractPolicies.ToDictionary(
            static policy => policy.ContractTypeName,
            StringComparer.Ordinal);
        sb.AppendLine("    private static readonly SharpLinkGeneratedContractCodecSet[] __contractCodecSets = new SharpLinkGeneratedContractCodecSet[]");
        sb.AppendLine("    {");
        foreach (var contract in contracts)
        {
            policyByContract.TryGetValue(contract.FullName, out var policy);
            var ownedByType = policy?.OwnedCodecs.ToDictionary(static codec => codec.TypeName, StringComparer.Ordinal)
                ?? new Dictionary<string, GeneratedCodecModel>(StringComparer.Ordinal);
            var finalCodecs = policy?.Codecs
                .Select(codec => ownedByType.TryGetValue(codec.TypeName, out var owned) ? owned : codec)
                .OrderBy(static codec => codec.TypeName, StringComparer.Ordinal)
                .ToArray() ?? [];
            var contractDependencies = contract.AssemblyDependencies
                .Concat(policy?.Dependencies ?? ImmutableArray<string>.Empty)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static dependency => dependency, StringComparer.Ordinal)
                .ToArray();

            sb.AppendLine("        new SharpLinkGeneratedContractCodecSet(");
            sb.AppendLine($"            typeof({contract.FullName}),");
            sb.AppendLine($"            {(policy?.HasCompileTimePolicy == true ? "true" : "false")},");
            sb.AppendLine("            Array.AsReadOnly(new IRpcGeneratedCodecFactory[]");
            sb.AppendLine("            {");
            foreach (var codec in finalCodecs)
                sb.AppendLine($"                new {codec.CodecName}.Factory(),");
            sb.AppendLine("            }),");
            sb.AppendLine("            Array.AsReadOnly(new string[]");
            sb.AppendLine("            {");
            foreach (var dependency in contractDependencies)
                sb.AppendLine($"                \"{EscapeString(dependency)}\",");
            sb.AppendLine("            })),");
        }
        sb.AppendLine("    };");
    }

    private static string BuildCompileTimeDescriptor(
        RpcInterfaceModel[] contracts,
        RpcServiceModel[] services,
        ImmutableArray<GeneratedCodecModel> codecs,
        ImmutableArray<GeneratedContractCodecPolicy> contractPolicies)
    {
        var sb = new StringBuilder();
        foreach (var contract in contracts)
            sb.Append("C:").Append(contract.Hash).Append(':').Append(contract.FullName).Append(':').Append(contract.Fingerprint).Append(';');
        foreach (var service in services)
            sb.Append("S:").Append(service.Interface.Hash).Append(':').Append(service.ServiceFullName).Append(':').Append(service.Lifetime).Append(';');
        foreach (var codec in codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
            sb.Append("D:").Append(codec.TypeName).Append(':').Append(codec.SchemaId).Append(';');
        foreach (var policy in contractPolicies.OrderBy(static policy => policy.ContractTypeName, StringComparer.Ordinal))
        {
            sb.Append("P:").Append(policy.ContractTypeName).Append(':').Append(policy.HasCompileTimePolicy ? '1' : '0').Append(':');
            foreach (var codec in policy.Codecs.OrderBy(static codec => codec.TypeName, StringComparer.Ordinal))
                sb.Append(codec.TypeName).Append('=').Append(codec.SchemaId).Append(',');
            sb.Append(';');
        }
        return sb.ToString();
    }

    private static string GetGeneratedContractTypeName(RpcInterfaceModel contract, string suffix)
        => string.IsNullOrEmpty(contract.Namespace)
            ? $"global::{contract.Name}_{suffix}"
            : $"global::{contract.Namespace}.{contract.Name}_{suffix}";

    private static string RemoveGlobalPrefix(string value)
        => value.StartsWith("global::", StringComparison.Ordinal)
            ? value.Substring("global::".Length)
            : value;
}
