namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private const string GeneratedAssemblyManifestAttributeMetadataName =
        "SharpLink.Abstractions.SharpLinkGeneratedAssemblyManifestAttribute";

    private static EquatableArray<ReferencedManifestBootstrapModel> AnalyzeReferencedManifestBootstraps(
        Compilation compilation,
        CancellationToken cancellationToken)
    {
        var manifests = new HashSet<ReferencedManifestBootstrapModel>();
        foreach (var reference in compilation.References)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly)
                continue;

            foreach (var attribute in assembly.GetAttributes())
            {
                if (attribute.AttributeClass?.ToDisplayString() != GeneratedAssemblyManifestAttributeMetadataName ||
                    attribute.ConstructorArguments.Length != 4 ||
                    attribute.ConstructorArguments[0].Value is not INamedTypeSymbol manifestType ||
                    attribute.ConstructorArguments[1].Value is not 4 ||
                    attribute.ConstructorArguments[2].Value is not 2 ||
                    attribute.ConstructorArguments[3].Value is not string generatorVersion ||
                    string.IsNullOrWhiteSpace(generatorVersion) ||
                    !SymbolEqualityComparer.Default.Equals(manifestType.ContainingAssembly, assembly))
                {
                    continue;
                }

                var hasRegisterMethod = manifestType.GetMembers("Register")
                    .OfType<IMethodSymbol>()
                    .Any(static method =>
                        method.IsStatic &&
                        method.DeclaredAccessibility == Accessibility.Public &&
                        method.MethodKind == MethodKind.Ordinary &&
                        method.Arity == 0 &&
                        method.Parameters.Length == 0 &&
                        method.ReturnsVoid);
                var hasInstance = manifestType.GetMembers("Instance")
                    .Any(static member =>
                        member is IFieldSymbol &&
                        member.IsStatic &&
                        member.DeclaredAccessibility == Accessibility.Public);
                if (!hasRegisterMethod && !hasInstance)
                    continue;

                manifests.Add(new ReferencedManifestBootstrapModel(
                    assembly.Identity.ToString(),
                    manifestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    hasRegisterMethod));
            }
        }

        return manifests
            .OrderBy(static manifest => manifest.AssemblyIdentity, StringComparer.Ordinal)
            .ThenBy(static manifest => manifest.ManifestTypeName, StringComparer.Ordinal)
            .ToImmutableArray();
    }

    private static string GenerateReferencedManifestBootstrap(
        EquatableArray<ReferencedManifestBootstrapModel> manifests)
    {
        if (manifests.Length == 0)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("internal static class __SharpLinkGeneratedReferencedAssemblyBootstrap");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterReferencedAssemblies()");
        sb.AppendLine("    {");
        foreach (var manifest in manifests)
        {
            if (manifest.HasRegisterMethod)
                sb.AppendLine($"        {manifest.ManifestTypeName}.Register();");
            else
                sb.AppendLine($"        global::SharpLink.Abstractions.SharpLinkGeneratedAssemblyCatalog.Register({manifest.ManifestTypeName}.Instance);");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
