namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateCodecs(
        ImmutableArray<GeneratedCodecModel> codecs,
        DtoCodecAnalysisResult dtoAnalysis)
    {
        var emittedCodecs = codecs
            .GroupBy(static codec => codec.CodecName, StringComparer.Ordinal)
            .Select(static group => group.First())
            .ToImmutableArray();
        var dtoByCodecName = dtoAnalysis.Codecs
            .Concat(dtoAnalysis.ContractCodecs)
            .GroupBy(static codec => codec.CodecName, StringComparer.Ordinal)
            .ToDictionary(
                static group => group.Key,
                static group => group.First(),
                StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        AppendAdapterCodecHolders(sb, emittedCodecs);

        if (emittedCodecs.Any(static codec =>
                codec.Kind == GeneratedCodecKind.Dto &&
                codec.Members.Any(static member => member.Kind == GeneratedMemberKind.String)))
            AppendGeneratedUtf16Helper(sb);

        foreach (var codec in emittedCodecs)
        {
            if (codec.Kind == GeneratedCodecKind.Adapter)
                AppendAdapterCodecFactory(sb, codec);
            else if (codec.Kind == GeneratedCodecKind.Custom)
                AppendCustomCodecFactory(sb, codec);
            else if (codec.Kind == GeneratedCodecKind.Dto)
            {
                if (!dtoByCodecName.TryGetValue(codec.CodecName, out var dto))
                {
                    throw new InvalidOperationException(
                        $"DTO analysis result is missing emitter model '{codec.CodecName}'.");
                }
                AppendDtoCodec(sb, dto);
            }
            else
                AppendCollectionCodec(sb, codec);
        }

        return sb.ToString();
    }

    private static string GetWireType(int fixedSize) => fixedSize switch
    {
        1 => "RpcGeneratedWireType.Fixed1",
        2 => "RpcGeneratedWireType.Fixed2",
        4 => "RpcGeneratedWireType.Fixed4",
        8 => "RpcGeneratedWireType.Fixed8",
        16 => "RpcGeneratedWireType.Fixed16",
        _ => throw new InvalidOperationException("Unsupported generated fixed size.")
    };

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string? GetSemanticFixedMethod(string typeName)
        => typeName.Replace("global::", string.Empty) switch
        {
            "System.Text.Rune" => "Rune",
            "decimal" or "System.Decimal" => "Decimal",
            "System.DateOnly" => "DateOnly",
            "System.DateTime" => "DateTime",
            "System.TimeOnly" => "TimeOnly",
            "System.DateTimeOffset" => "DateTimeOffset",
            _ => null
        };
}
