namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateStub(string manifestTypeName, RpcInterfaceModel model)
    {
        var body = new StringBuilder();
        AppendStubClassBody(body, model);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {manifestTypeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private sealed class __Stub_{GetContractArtifactIdentity(model)} : IRpcStub");
        sb.AppendLine("    {");
        sb.Append(Indent(body.ToString(), "    "));
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendStubClassBody(StringBuilder sb, RpcInterfaceModel model)
    {
        var noReturnMethods = model.Methods.Where(m => m.IsVoid || m.IsStreamReturn).ToArray();
        var responseMethods = model.Methods.Where(m => !m.IsVoid && !m.IsStreamReturn).ToArray();

        sb.AppendLine($"    public long InterfaceHash => {model.Hash}L;");
        AppendStubCodecFieldsAndConstructor(sb, model);
        AppendSizeFieldsByType(sb, model.Methods);
        AppendCancellationSupport(sb, model.Methods);
        AppendMethodDescriptors(sb, model);
        sb.AppendLine($$"""
                            private static void __SerializeResponse<T>(T result, bool responseNullable, IRpcCodec<T> codec, IBufferWriter<byte> output)
                            {
                                if (!responseNullable && default(T) is null && result is null)
                                    throw new SharpLinkException(SharpLinkErrorCode.Internal, "A non-nullable RPC response was null.");
                                codec.Serialize(result, output);
                            }

                            private static async ValueTask __AwaitTaskResultAsync<T>(Task<T> task, bool responseNullable, IRpcCodec<T> codec, IBufferWriter<byte> output)
                            {
                                var result = await task.ConfigureAwait(false);
                                __SerializeResponse(result, responseNullable, codec, output);
                            }

                            private static async ValueTask __AwaitValueTaskResultAsync<T>(ValueTask<T> task, bool responseNullable, IRpcCodec<T> codec, IBufferWriter<byte> output)
                            {
                                var result = await task.ConfigureAwait(false);
                                __SerializeResponse(result, responseNullable, codec, output);
                            }

                            private static async ValueTask __AwaitTaskIgnoreAsync<T>(Task<T> task)
                            {
                                _ = await task.ConfigureAwait(false);
                            }

                            private static async ValueTask __AwaitValueTaskIgnoreAsync<T>(ValueTask<T> task)
                            {
                                _ = await task.ConfigureAwait(false);
                            }

                            public ValueTask InvokeNoReturnAsync(object service, IRpcGeneratedServerBridge bridge, long methodHash, long requestId, ReadOnlySequence<byte> args)
                                => InvokeNoReturnCoreAsync(service, bridge, methodHash, requestId, args, CancellationToken.None);

                            public ValueTask InvokeNoReturnCancellableAsync(object service, IRpcGeneratedServerBridge bridge, long methodHash, long requestId, ReadOnlySequence<byte> args, CancellationToken cancellationToken)
                                => InvokeNoReturnCoreAsync(service, bridge, methodHash, requestId, args, cancellationToken);

                            private ValueTask InvokeNoReturnCoreAsync(object service, IRpcGeneratedServerBridge bridge, long methodHash, long requestId, ReadOnlySequence<byte> args, CancellationToken cancellationToken)
                            {
                                var impl = ({{model.FullName}})service;
                                var reader = new SequenceReader<byte>(args);
                        """);

        if (noReturnMethods.Length == 0)
        {
            sb.AppendLine("""
                                throw new SharpLinkException(SharpLinkErrorCode.Unimplemented, "Method is not implemented.");
                            }
""");
        }
        else
        {
            var needsCompletedReturn = noReturnMethods.Any(static m => !m.IsStreamReturn);
            sb.AppendLine("""
        switch (methodHash)
        {
""");
            AppendStubDispatchCases(sb, noReturnMethods, model.Hash, writeResponse: false);
            sb.AppendLine("            default: throw new SharpLinkException(SharpLinkErrorCode.Unimplemented, \"Method is not implemented.\");");
            sb.AppendLine("        }");
            if (needsCompletedReturn)
                sb.AppendLine("        return ValueTask.CompletedTask;");
            sb.AppendLine("    }");
        }

        sb.AppendLine($$"""
                            public ValueTask InvokeAsync(object service, IRpcGeneratedServerBridge bridge, long methodHash, long requestId, ReadOnlySequence<byte> args, IBufferWriter<byte> output)
                                => InvokeCoreAsync(service, bridge, methodHash, requestId, args, output, CancellationToken.None);

                            public ValueTask InvokeCancellableAsync(object service, IRpcGeneratedServerBridge bridge, long methodHash, long requestId, ReadOnlySequence<byte> args, IBufferWriter<byte> output, CancellationToken cancellationToken)
                                => InvokeCoreAsync(service, bridge, methodHash, requestId, args, output, cancellationToken);

                            private ValueTask InvokeCoreAsync(object service, IRpcGeneratedServerBridge bridge, long methodHash, long requestId, ReadOnlySequence<byte> args, IBufferWriter<byte> output, CancellationToken cancellationToken)
                            {
                                var impl = ({{model.FullName}})service;
                                var reader = new SequenceReader<byte>(args);
                        """);

        if (responseMethods.Length == 0)
        {
            sb.AppendLine("""
                                throw new SharpLinkException(SharpLinkErrorCode.Unimplemented, "Method is not implemented.");
                            }
""");
        }
        else
        {
            sb.AppendLine("""
        switch (methodHash)
        {
""");
            AppendStubDispatchCases(sb, responseMethods, model.Hash, writeResponse: true);
            sb.AppendLine("            default: throw new SharpLinkException(SharpLinkErrorCode.Unimplemented, \"Method is not implemented.\");");
            sb.AppendLine("        }");
            sb.AppendLine("        return ValueTask.CompletedTask;");
            sb.AppendLine("    }");
        }

    }

    private static void AppendStubCodecFieldsAndConstructor(StringBuilder sb, RpcInterfaceModel model)
    {
        foreach (var method in model.Methods)
        {
            for (var parameterIndex = 0; parameterIndex < method.Parameters.Length; parameterIndex++)
            {
                var parameter = method.Parameters[parameterIndex];
                if (parameter.IsStream)
                {
                    sb.AppendLine(
                        $"    private readonly IRpcCodec<{parameter.DisplayStreamItemType}> {GetStubParameterCodecField(method, parameterIndex)};");
                }
                else if (parameter is
                {
                    IsCancellationToken: false,
                    IsCallOptions: false,
                    IsBlittable: false
                })
                {
                    sb.AppendLine(
                        $"    private readonly IRpcCodec<{parameter.DisplayType}> {GetStubParameterCodecField(method, parameterIndex)};");
                }
            }

            if (!method.IsVoid && !method.IsOneWay)
            {
                sb.AppendLine(
                    $"    private readonly IRpcCodec<{GetResponseType(method)}> {GetStubResponseCodecField(method)};");
            }
        }

        sb.AppendLine();
        sb.AppendLine($"    internal __Stub_{GetContractArtifactIdentity(model)}(IRpcCodecProvider codecs)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(codecs);");
        foreach (var method in model.Methods)
        {
            for (var parameterIndex = 0; parameterIndex < method.Parameters.Length; parameterIndex++)
            {
                var parameter = method.Parameters[parameterIndex];
                if (parameter.IsStream)
                {
                    sb.AppendLine(
                        $"        {GetStubParameterCodecField(method, parameterIndex)} = codecs.GetCodec<{parameter.DisplayStreamItemType}>();");
                }
                else if (parameter is
                {
                    IsCancellationToken: false,
                    IsCallOptions: false,
                    IsBlittable: false
                })
                {
                    sb.AppendLine(
                        $"        {GetStubParameterCodecField(method, parameterIndex)} = codecs.GetCodec<{parameter.DisplayType}>();");
                }
            }

            if (!method.IsVoid && !method.IsOneWay)
            {
                sb.AppendLine(
                    $"        {GetStubResponseCodecField(method)} = codecs.GetCodec<{GetResponseType(method)}>();");
            }
        }
        sb.AppendLine("    }");
    }

    private static string GetStubParameterCodecField(RpcMethodModel method, int parameterIndex)
        => $"__parameterCodec_{GetMethodSuffix(method)}_{parameterIndex}";

    private static string GetStubResponseCodecField(RpcMethodModel method)
        => $"__responseCodec_{GetMethodSuffix(method)}";

    private static void AppendCancellationSupport(StringBuilder sb, EquatableArray<RpcMethodModel> methods)
    {
        var cancellableMethods = methods
            .Where(static method => method.HasCancellationToken ||
                                    method.IsStreamReturn ||
                                    method.Parameters.Any(static parameter => parameter.IsStream))
            .ToArray();

        if (cancellableMethods.Length == 0)
        {
            sb.AppendLine("    public bool SupportsCancellation(long methodHash) => false;");
            return;
        }

        sb.AppendLine("    public bool SupportsCancellation(long methodHash)");
        sb.AppendLine("        => methodHash switch");
        sb.AppendLine("        {");
        foreach (var method in cancellableMethods)
            sb.AppendLine($"            {method.Hash}L => true,");
        sb.AppendLine("            _ => false");
        sb.AppendLine("        };");
    }

    private static void AppendMethodDescriptors(StringBuilder sb, RpcInterfaceModel model)
    {
        sb.AppendLine("    public bool TryGetMethodDescriptor(long methodHash, out RpcMethodDescriptor descriptor)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (methodHash)");
        sb.AppendLine("        {");
        foreach (var method in model.Methods)
        {
            var kind = GetMethodKind(method);
            var hasPayloadResponse = !method.IsOneWay && !method.IsVoid;
            var clientStreamCount = method.Parameters.Count(static parameter => parameter.IsStream);
            var hasClientStreams = clientStreamCount != 0;
            var methodTimeout = method.TimeoutSeconds is { } seconds
                ? $"TimeSpan.FromSeconds({seconds.ToString("R", InvariantCulture)}d)"
                : "null";
            sb.AppendLine($"            case {method.Hash}L:");
            sb.AppendLine($"                descriptor = new RpcMethodDescriptor({model.Hash}L, {method.Hash}L, RpcMethodKind.{kind}, {(hasPayloadResponse ? "true" : "false")}, {(hasClientStreams ? "true" : "false")}, {(method.HasTimeoutAttribute ? "true" : "false")}, {methodTimeout}, {(method.IsIdempotent ? "true" : "false")}, {clientStreamCount}, {(method.ResponseNullable ? "true" : "false")});");
            sb.AppendLine("                return true;");
        }
        sb.AppendLine("            default:");
        sb.AppendLine("                descriptor = default;");
        sb.AppendLine("                return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendStubDispatchCases(
        StringBuilder sb,
        IEnumerable<RpcMethodModel> methods,
        long interfaceHash,
        bool writeResponse)
    {
        foreach (var method in methods)
        {
            sb.AppendLine($"            case {method.Hash}L:");
            sb.AppendLine("            {");
            var indexedParameters = method.Parameters
                .Select(static (parameter, index) => (Parameter: parameter, Index: index))
                .ToArray();
            var streamParams = indexedParameters.Where(static item => item.Parameter.IsStream).ToArray();
            var blittableParams = method.Parameters.Where(p => !p.IsStream && p is { IsCancellationToken: false, IsCallOptions: false, IsBlittable: true }).ToList();
            var complexParams = indexedParameters.Where(static item =>
                !item.Parameter.IsStream && item.Parameter is
                {
                    IsCancellationToken: false,
                    IsCallOptions: false,
                    IsBlittable: false
                }).ToArray();
            var streamId = 1;

            foreach (var item in streamParams)
            {
                var p = item.Parameter;
                sb.AppendLine($"                IAsyncEnumerable<{p.DisplayStreamItemType}> stream_{p.Name};");
            }

            foreach (var p in method.Parameters.Where(p => !p.IsStream))
            {
                sb.AppendLine($"                {p.DisplayType} arg_{p.Name};");
            }

            foreach (var p in method.Parameters.Where(p => p.IsCancellationToken))
            {
                sb.AppendLine($"                arg_{p.Name} = cancellationToken;");
            }

            foreach (var p in method.Parameters.Where(p => p.IsCallOptions))
            {
                sb.AppendLine($"                arg_{p.Name} = new global::SharpLink.Sdk.SharpLinkCallOptions");
                sb.AppendLine("                {");
                sb.AppendLine("                    Deadline = SharpLinkCallContext.Current?.Deadline,");
                sb.AppendLine("                    Metadata = SharpLinkCallContext.Current?.Metadata");
                sb.AppendLine("                };");
            }

            foreach (var p in blittableParams)
            {
                var sizeToken = GetSizeToken(p.Type);
                if (IsBooleanType(p.Type))
                {
                    sb.AppendLine($"                if (!reader.TryRead(out var marker_{p.Name}) || marker_{p.Name} is not (0 or 1)) throw RpcGeneratedCodecWire.DataLoss(\"Request Boolean marker is missing or non-canonical.\");");
                    sb.AppendLine($"                arg_{p.Name} = marker_{p.Name} == 1;");
                    continue;
                }
                sb.AppendLine($"                if (reader.Remaining < {sizeToken}) throw RpcGeneratedCodecWire.DataLoss(\"Request fixed argument is truncated.\");");
                sb.AppendLine($"                if (reader.UnreadSpan.Length >= {sizeToken})");
                sb.AppendLine("                {");
                sb.AppendLine($"                    arg_{p.Name} = System.Runtime.CompilerServices.Unsafe.ReadUnaligned<{p.Type}>(in System.Runtime.InteropServices.MemoryMarshal.GetReference(reader.UnreadSpan));");
                sb.AppendLine("                }");
                sb.AppendLine("                else");
                sb.AppendLine("                {");
                sb.AppendLine($"                    Span<byte> tmp_{p.Name} = stackalloc byte[{sizeToken}];");
                sb.AppendLine($"                    if (!reader.TryCopyTo(tmp_{p.Name})) throw RpcGeneratedCodecWire.DataLoss(\"Request fixed argument is truncated.\");");
                sb.AppendLine($"                    arg_{p.Name} = System.Runtime.CompilerServices.Unsafe.ReadUnaligned<{p.Type}>(in System.Runtime.InteropServices.MemoryMarshal.GetReference(tmp_{p.Name}));");
                sb.AppendLine("                }");
                sb.AppendLine($"                reader.Advance({sizeToken});");
            }

            foreach (var item in complexParams)
            {
                var p = item.Parameter;
                var codecField = GetStubParameterCodecField(method, item.Index);
                sb.AppendLine($"                if (!reader.TryReadLittleEndian(out int len_{p.Name})) throw RpcGeneratedCodecWire.DataLoss(\"Request argument length is truncated.\");");
                sb.AppendLine($"                if (len_{p.Name} < 0 || reader.Remaining < len_{p.Name}) throw RpcGeneratedCodecWire.DataLoss(\"Request argument length is invalid.\");");
                sb.AppendLine($"                var seq_{p.Name} = reader.UnreadSequence.Slice(0, len_{p.Name});");
                if (p.IsValueType || p.IsNullableReference)
                {
                    sb.AppendLine($"                arg_{p.Name} = {codecField}.Deserialize(in seq_{p.Name});");
                }
                else
                {
                    sb.AppendLine($"                arg_{p.Name} = {codecField}.Deserialize(in seq_{p.Name}) ?? throw RpcGeneratedCodecWire.DataLoss(\"Argument {p.Name} is null.\");");
                }

                sb.AppendLine($"                reader.Advance(len_{p.Name});");
            }

            sb.AppendLine("                if (reader.Remaining != 0) throw RpcGeneratedCodecWire.DataLoss(\"Request contains trailing data.\");");

            foreach (var item in streamParams)
            {
                var p = item.Parameter;
                sb.AppendLine($"                stream_{p.Name} = bridge.CreateInboundStream(requestId, (ushort){streamId}, {GetStubParameterCodecField(method, item.Index)}, {(p.PayloadNullable ? "true" : "false")}, cancellationToken);");
                streamId++;
            }

            var callArgs = string.Join(", ", method.Parameters.Select(p => p.IsStream ? $"stream_{p.Name}" : $"arg_{p.Name}"));
            var callLine = $"impl.{EscapeIdentifier(method.Name)}({callArgs})";

            if (method.IsStreamReturn)
            {
                sb.AppendLine($"                var resultStream = {callLine};");
                sb.AppendLine($"                return bridge.PumpOutboundStreamAsync(requestId, 0, resultStream, {GetStubResponseCodecField(method)}, {(method.ResponseNullable ? "true" : "false")}, {interfaceHash}L, {method.Hash}L, cancellationToken);");
            }
            else if (method.IsVoid)
            {
                if (method.ReturnsValueTask)
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (!pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                    return pending;");
                }
                else
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (!pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                    return new ValueTask(pending);");
                }
            }
            else
            {
                if (method.ReturnsValueTask)
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                {");
                    if (writeResponse)
                        sb.AppendLine($"                    __SerializeResponse(pending.Result, {(method.ResponseNullable ? "true" : "false")}, {GetStubResponseCodecField(method)}, output);");
                    sb.AppendLine("                }");
                    sb.AppendLine("                else");
                    sb.AppendLine("                {");
                    sb.AppendLine(writeResponse
                        ? $"                    return __AwaitValueTaskResultAsync(pending, {(method.ResponseNullable ? "true" : "false")}, {GetStubResponseCodecField(method)}, output);"
                        : "                    return __AwaitValueTaskIgnoreAsync(pending);");
                    sb.AppendLine("                }");
                }
                else
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                {");
                    if (writeResponse)
                        sb.AppendLine($"                    __SerializeResponse(pending.GetAwaiter().GetResult(), {(method.ResponseNullable ? "true" : "false")}, {GetStubResponseCodecField(method)}, output);");
                    sb.AppendLine("                }");
                    sb.AppendLine("                else");
                    sb.AppendLine("                {");
                    sb.AppendLine(writeResponse
                        ? $"                    return __AwaitTaskResultAsync(pending, {(method.ResponseNullable ? "true" : "false")}, {GetStubResponseCodecField(method)}, output);"
                        : "                    return __AwaitTaskIgnoreAsync(pending);");
                    sb.AppendLine("                }");
                }
            }

            if (!method.IsStreamReturn)
                sb.AppendLine("                break;");
            sb.AppendLine("            }");
        }
    }

    private static void AppendSizeFieldsByType(StringBuilder sb, EquatableArray<RpcMethodModel> methods)
    {
        var blittableTypes = methods
            .SelectMany(m => m.Parameters)
            .Where(p => !p.IsStream && p is { IsCancellationToken: false, IsCallOptions: false, IsBlittable: true })
            .Select(p => p.Type)
            .Distinct()
            .ToArray();

        foreach (var type in blittableTypes)
        {
            if (TryGetConstantSize(type, out _))
                continue;

            var fieldName = GetSizeFieldNameByType(type);
            sb.AppendLine($"    private static readonly int {fieldName} = {GetSizeExpression(type)};");
        }
    }

    private static string GetSizeFieldNameByType(string typeName)
    {
        var sanitized = typeName
            .Replace("global::", "")
            .Replace(".", "_")
            .Replace("::", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "")
            .Replace("(", "_")
            .Replace(")", "_")
            .Replace("[", "_")
            .Replace("]", "_");

        return $"__size_type_{sanitized}_{Hashing.GetIdentifierHash(typeName)}";
    }

    private static string GetSizeToken(string typeName)
    {
        if (TryGetConstantSize(typeName, out var size))
            return size.ToString();

        return GetSizeFieldNameByType(typeName);
    }

    private static string GetSizeExpression(string typeName)
    {
        return $"System.Runtime.CompilerServices.Unsafe.SizeOf<{typeName}>()";
    }

    private static bool IsBooleanType(string typeName)
        => typeName is "bool" or "System.Boolean" or "global::System.Boolean";

    private static bool TryGetConstantSize(string typeName, out int size)
    {
        var t = typeName.Replace("global::", "");
        switch (t)
        {
            case "bool":
            case "System.Boolean":
            case "byte":
            case "System.Byte":
            case "sbyte":
            case "System.SByte":
                size = 1; return true;
            case "short":
            case "System.Int16":
            case "ushort":
            case "System.UInt16":
            case "char":
            case "System.Char":
                size = 2; return true;
            case "int":
            case "System.Int32":
            case "uint":
            case "System.UInt32":
            case "float":
            case "System.Single":
                size = 4; return true;
            case "long":
            case "System.Int64":
            case "ulong":
            case "System.UInt64":
            case "double":
            case "System.Double":
            case "System.DateTime":
            case "System.TimeSpan":
                size = 8; return true;
            case "decimal":
            case "System.Decimal":
            case "System.Guid":
                size = 16; return true;
            default:
                size = 0; return false;
        }
    }
}
