namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateUnsafeBlitRequirements(
        ImmutableArray<GeneratedUnsafeBlitRequirementModel> requirements)
    {
        if (requirements.IsDefaultOrEmpty)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class __SharpLinkGeneratedUnsafeBlitRequirementsInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        foreach (var requirement in requirements.OrderBy(static item => item.TypeName, StringComparer.Ordinal))
        {
            sb.AppendLine(
                $"        SharpLinkGeneratedUnsafeBlitCatalog.Register(typeof({requirement.TypeName}), {requirement.NativePointerWidth.ToString(InvariantCulture)}, {(requirement.RequiresDateTimeOffsetRawAbi ? "true" : "false")});");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
