namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateStub(RpcInterfaceModel model)
    {
        var nsDeclaration = string.IsNullOrEmpty(model.Namespace) ? "" : $"namespace {model.Namespace};";
        var noReturnMethods = model.Methods.Where(m => m.IsVoid || m.IsStreamReturn).ToArray();
        var responseMethods = model.Methods.Where(m => !m.IsVoid && !m.IsStreamReturn).ToArray();

        var sb = new StringBuilder();
        sb.AppendLine($$"""
                        // <auto-generated/>
                        #nullable enable
                        using SharpLink.Abstractions;
                        using System;
                        using System.Buffers;
                        using System.Collections.Generic;
                        using System.IO;
                        using System.Runtime.CompilerServices;
                        using System.Threading;
                        using System.Threading.Tasks;

                        {{nsDeclaration}}

                        public sealed class {{model.Name}}_Stub : IRpcStub
                        {
                            public long InterfaceHash => {{model.Hash}}L;
                        """);
        AppendSizeFieldsByType(sb, model.Methods);
        AppendCancellationSupport(sb, model.Methods);
        AppendMethodDescriptors(sb, model);
        sb.AppendLine($$"""
                            private static async ValueTask __AwaitTaskResultAsync<T>(Task<T> task, IRpcSession session, IRpcByteBufferWriter output)
                            {
                                var result = await task.ConfigureAwait(false);
                                session.RuntimeContext.Codecs.GetCodec<T>().Serialize(result, output);
                            }

                            private static async ValueTask __AwaitValueTaskResultAsync<T>(ValueTask<T> task, IRpcSession session, IRpcByteBufferWriter output)
                            {
                                var result = await task.ConfigureAwait(false);
                                session.RuntimeContext.Codecs.GetCodec<T>().Serialize(result, output);
                            }

                            private static async ValueTask __AwaitTaskIgnoreAsync<T>(Task<T> task)
                            {
                                _ = await task.ConfigureAwait(false);
                            }

                            private static async ValueTask __AwaitValueTaskIgnoreAsync<T>(ValueTask<T> task)
                            {
                                _ = await task.ConfigureAwait(false);
                            }

                            private static async ValueTask __PumpStreamAsync<T>(
                                IAsyncEnumerable<T> stream,
                                IRpcSession session,
                                long requestId,
                                long contractId,
                                long methodId,
                                CancellationToken cancellationToken)
                            {
                                try
                                {
                                    await foreach (var item in stream.WithCancellation(cancellationToken).ConfigureAwait(false))
                                        await SharpLink.Runtime.RpcSessionExtensions.SendStreamChunkAsync(
                                            session, requestId, 0, item, cancellationToken).ConfigureAwait(false);

                                    SharpLink.Runtime.RpcSessionExtensions.SendStreamCompleteAsync(session, requestId, 0);
                                }
                                catch (Exception ex)
                                {
                                    SharpLink.Runtime.RpcSessionExtensions.SendStreamErrorAsync(
                                        session, requestId, 0, ex, contractId, methodId);
                                }
                            }

                            public ValueTask InvokeNoReturnAsync(object service, IRpcSession session, long methodHash, long requestId, ReadOnlySequence<byte> args)
                                => InvokeNoReturnCoreAsync(service, session, methodHash, requestId, args, CancellationToken.None);

                            public ValueTask InvokeNoReturnCancellableAsync(object service, IRpcSession session, long methodHash, long requestId, ReadOnlySequence<byte> args, CancellationToken cancellationToken)
                                => InvokeNoReturnCoreAsync(service, session, methodHash, requestId, args, cancellationToken);

                            private ValueTask InvokeNoReturnCoreAsync(object service, IRpcSession session, long methodHash, long requestId, ReadOnlySequence<byte> args, CancellationToken cancellationToken)
                            {
                                var impl = ({{model.FullName}})service;
                                var reader = new SequenceReader<byte>(args);
                        """);

        if (noReturnMethods.Length == 0)
        {
            sb.AppendLine("""
                                throw new RpcException("Method not found");
                            }
""");
        }
        else
        {
            var needsCompletedReturn = noReturnMethods.Any(static m => !m.IsStreamReturn);
            sb.AppendLine("""
        switch (methodHash)
        {
""");
            AppendStubDispatchCases(sb, noReturnMethods, model.Hash, writeResponse: false);
            sb.AppendLine("            default: throw new SharpLinkException(SharpLinkErrorCode.Unimplemented, \"Method is not implemented.\");");
            sb.AppendLine("        }");
            if (needsCompletedReturn)
                sb.AppendLine("        return ValueTask.CompletedTask;");
            sb.AppendLine("    }");
        }

        sb.AppendLine($$"""
                            public ValueTask InvokeAsync(object service, IRpcSession session, long methodHash, long requestId, ReadOnlySequence<byte> args, IRpcByteBufferWriter output)
                                => InvokeCoreAsync(service, session, methodHash, requestId, args, output, CancellationToken.None);

                            public ValueTask InvokeCancellableAsync(object service, IRpcSession session, long methodHash, long requestId, ReadOnlySequence<byte> args, IRpcByteBufferWriter output, CancellationToken cancellationToken)
                                => InvokeCoreAsync(service, session, methodHash, requestId, args, output, cancellationToken);

                            private ValueTask InvokeCoreAsync(object service, IRpcSession session, long methodHash, long requestId, ReadOnlySequence<byte> args, IRpcByteBufferWriter output, CancellationToken cancellationToken)
                            {
                                var impl = ({{model.FullName}})service;
                                var reader = new SequenceReader<byte>(args);
                        """);

        if (responseMethods.Length == 0)
        {
            sb.AppendLine("""
                                throw new RpcException("Method not found");
                            }
""");
        }
        else
        {
            sb.AppendLine("""
        switch (methodHash)
        {
""");
            AppendStubDispatchCases(sb, responseMethods, model.Hash, writeResponse: true);
            sb.AppendLine("            default: throw new SharpLinkException(SharpLinkErrorCode.Unimplemented, \"Method is not implemented.\");");
            sb.AppendLine("        }");
            sb.AppendLine("        return ValueTask.CompletedTask;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendCancellationSupport(StringBuilder sb, EquatableArray<RpcMethodModel> methods)
    {
        var cancellableMethods = methods
            .Where(static method => method.HasCancellationToken ||
                                    method.IsStreamReturn ||
                                    method.Parameters.Any(static parameter => parameter.IsStream))
            .ToArray();

        if (cancellableMethods.Length == 0)
        {
            sb.AppendLine("    public bool SupportsCancellation(long methodHash) => false;");
            return;
        }

        sb.AppendLine("    public bool SupportsCancellation(long methodHash)");
        sb.AppendLine("        => methodHash switch");
        sb.AppendLine("        {");
        foreach (var method in cancellableMethods)
            sb.AppendLine($"            {method.Hash}L => true,");
        sb.AppendLine("            _ => false");
        sb.AppendLine("        };");
    }

    private static void AppendMethodDescriptors(StringBuilder sb, RpcInterfaceModel model)
    {
        sb.AppendLine("    public bool TryGetMethodDescriptor(long methodHash, out RpcMethodDescriptor descriptor)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (methodHash)");
        sb.AppendLine("        {");
        foreach (var method in model.Methods)
        {
            var kind = GetMethodKind(method);
            var hasPayloadResponse = !method.IsOneWay && !method.IsVoid;
            var hasClientStreams = method.Parameters.Any(static parameter => parameter.IsStream);
            var methodTimeout = method.TimeoutSeconds is { } seconds
                ? $"TimeSpan.FromSeconds({seconds.ToString("R", InvariantCulture)}d)"
                : "null";
            sb.AppendLine($"            case {method.Hash}L:");
            sb.AppendLine($"                descriptor = new RpcMethodDescriptor({model.Hash}L, {method.Hash}L, RpcMethodKind.{kind}, {(hasPayloadResponse ? "true" : "false")}, {(hasClientStreams ? "true" : "false")}, {(method.HasTimeoutAttribute ? "true" : "false")}, {methodTimeout}, {(method.IsIdempotent ? "true" : "false")});");
            sb.AppendLine("                return true;");
        }
        sb.AppendLine("            default:");
        sb.AppendLine("                descriptor = default;");
        sb.AppendLine("                return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendStubDispatchCases(
        StringBuilder sb,
        IEnumerable<RpcMethodModel> methods,
        long interfaceHash,
        bool writeResponse)
    {
        foreach (var method in methods)
        {
            sb.AppendLine($"            case {method.Hash}L:");
            sb.AppendLine("            {");
            var streamParams = method.Parameters.Where(p => p.IsStream).ToList();
            var blittableParams = method.Parameters.Where(p => !p.IsStream && p is { IsCancellationToken: false, IsCallOptions: false, IsBlittable: true }).ToList();
            var complexParams = method.Parameters.Where(p => !p.IsStream && p is { IsCancellationToken: false, IsCallOptions: false, IsBlittable: false }).ToList();
            var streamId = 1;

            foreach (var p in streamParams)
            {
                sb.AppendLine($"                SharpLink.Runtime.PooledAsyncStreamDispatcher<{p.StreamItemType}> dispatcher_{p.Name};");
            }

            foreach (var p in method.Parameters.Where(p => !p.IsStream))
            {
                sb.AppendLine($"                {p.Type} arg_{p.Name};");
            }

            foreach (var p in method.Parameters.Where(p => p.IsCancellationToken))
            {
                sb.AppendLine($"                arg_{p.Name} = cancellationToken;");
            }

            foreach (var p in method.Parameters.Where(p => p.IsCallOptions))
            {
                sb.AppendLine($"                arg_{p.Name} = new global::SharpLink.Sdk.SharpLinkCallOptions");
                sb.AppendLine("                {");
                sb.AppendLine("                    Deadline = SharpLinkCallContext.Current?.Deadline,");
                sb.AppendLine("                    Metadata = SharpLinkCallContext.Current?.Metadata");
                sb.AppendLine("                };");
            }

            foreach (var p in blittableParams)
            {
                var sizeToken = GetSizeToken(p.Type);
                sb.AppendLine($"                if (reader.Remaining < {sizeToken}) throw new InvalidDataException();");
                sb.AppendLine($"                if (reader.UnreadSpan.Length >= {sizeToken})");
                sb.AppendLine("                {");
                sb.AppendLine($"                    arg_{p.Name} = System.Runtime.CompilerServices.Unsafe.ReadUnaligned<{p.Type}>(in System.Runtime.InteropServices.MemoryMarshal.GetReference(reader.UnreadSpan));");
                sb.AppendLine("                }");
                sb.AppendLine("                else");
                sb.AppendLine("                {");
                sb.AppendLine($"                    Span<byte> tmp_{p.Name} = stackalloc byte[{sizeToken}];");
                sb.AppendLine($"                    if (!reader.TryCopyTo(tmp_{p.Name})) throw new InvalidDataException();");
                sb.AppendLine($"                    arg_{p.Name} = System.Runtime.CompilerServices.Unsafe.ReadUnaligned<{p.Type}>(in System.Runtime.InteropServices.MemoryMarshal.GetReference(tmp_{p.Name}));");
                sb.AppendLine("                }");
                sb.AppendLine($"                reader.Advance({sizeToken});");
            }

            foreach (var p in complexParams)
            {
                sb.AppendLine($"                if (!reader.TryReadLittleEndian(out int len_{p.Name})) throw new InvalidDataException();");
                sb.AppendLine($"                if (len_{p.Name} < 0 || reader.Remaining < len_{p.Name}) throw new InvalidDataException();");
                sb.AppendLine($"                var seq_{p.Name} = reader.UnreadSequence.Slice(0, len_{p.Name});");
                if (p.IsValueType || p.IsNullableReference)
                {
                    sb.AppendLine($"                arg_{p.Name} = session.RuntimeContext.Codecs.GetCodec<{p.Type}>().Deserialize(in seq_{p.Name});");
                }
                else
                {
                    sb.AppendLine($"                arg_{p.Name} = session.RuntimeContext.Codecs.GetCodec<{p.Type}>().Deserialize(in seq_{p.Name}) ?? throw new InvalidDataException(\"Argument {p.Name} is null.\");");
                }

                sb.AppendLine($"                reader.Advance(len_{p.Name});");
            }

            sb.AppendLine("                if (reader.Remaining != 0) throw new InvalidDataException();");

            foreach (var p in streamParams)
            {
                sb.AppendLine($"                dispatcher_{p.Name} = SharpLink.Runtime.PooledAsyncStreamDispatcher<{p.StreamItemType}>.Rent(cancellationToken, session.RuntimeContext.Codecs);");
                sb.AppendLine($"                session.StreamManager.Register(requestId, (ushort){streamId}, dispatcher_{p.Name});");
                streamId++;
            }

            var callArgs = string.Join(", ", method.Parameters.Select(p => p.IsStream ? $"dispatcher_{p.Name}" : $"arg_{p.Name}"));
            var callLine = $"impl.{method.Name}({callArgs})";

            if (method.IsStreamReturn)
            {
                sb.AppendLine($"                var resultStream = {callLine};");
                sb.AppendLine($"                return __PumpStreamAsync(resultStream, session, requestId, {interfaceHash}L, {method.Hash}L, cancellationToken);");
            }
            else if (method.IsVoid)
            {
                if (method.ReturnType.Contains("ValueTask"))
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (!pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                    return pending;");
                }
                else
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (!pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                    return new ValueTask(pending);");
                }
            }
            else
            {
                if (method.ReturnType.Contains("ValueTask"))
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                {");
                    if (writeResponse)
                        sb.AppendLine($"                    session.RuntimeContext.Codecs.GetCodec<{method.GenericArgumentType}>().Serialize(pending.Result, output);");
                    sb.AppendLine("                }");
                    sb.AppendLine("                else");
                    sb.AppendLine("                {");
                    sb.AppendLine(writeResponse
                        ? "                    return __AwaitValueTaskResultAsync(pending, session, output);"
                        : "                    return __AwaitValueTaskIgnoreAsync(pending);");
                    sb.AppendLine("                }");
                }
                else
                {
                    sb.AppendLine($"                var pending = {callLine};");
                    sb.AppendLine("                if (pending.IsCompletedSuccessfully)");
                    sb.AppendLine("                {");
                    if (writeResponse)
                        sb.AppendLine($"                    session.RuntimeContext.Codecs.GetCodec<{method.GenericArgumentType}>().Serialize(pending.GetAwaiter().GetResult(), output);");
                    sb.AppendLine("                }");
                    sb.AppendLine("                else");
                    sb.AppendLine("                {");
                    sb.AppendLine(writeResponse
                        ? "                    return __AwaitTaskResultAsync(pending, session, output);"
                        : "                    return __AwaitTaskIgnoreAsync(pending);");
                    sb.AppendLine("                }");
                }
            }

            if (!method.IsStreamReturn)
                sb.AppendLine("                break;");
            sb.AppendLine("            }");
        }
    }

    private static void AppendSizeFieldsByType(StringBuilder sb, EquatableArray<RpcMethodModel> methods)
    {
        var blittableTypes = methods
            .SelectMany(m => m.Parameters)
            .Where(p => !p.IsStream && p is { IsCancellationToken: false, IsCallOptions: false, IsBlittable: true })
            .Select(p => p.Type)
            .Distinct()
            .ToArray();

        foreach (var type in blittableTypes)
        {
            if (TryGetConstantSize(type, out _))
                continue;

            var fieldName = GetSizeFieldNameByType(type);
            sb.AppendLine($"    private static readonly int {fieldName} = {GetSizeExpression(type)};");
        }
    }

    private static string GetSizeFieldNameByType(string typeName)
    {
        var sanitized = typeName
            .Replace("global::", "")
            .Replace(".", "_")
            .Replace("::", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "")
            .Replace("(", "_")
            .Replace(")", "_")
            .Replace("[", "_")
            .Replace("]", "_");

        return $"__size_type_{sanitized}";
    }

    private static string GetSizeToken(string typeName)
    {
        if (TryGetConstantSize(typeName, out var size))
            return size.ToString();

        return GetSizeFieldNameByType(typeName);
    }

    private static string GetSizeExpression(string typeName)
    {
        return $"System.Runtime.CompilerServices.Unsafe.SizeOf<{typeName}>()";
    }

    private static bool TryGetConstantSize(string typeName, out int size)
    {
        var t = typeName.Replace("global::", "");
        switch (t)
        {
            case "bool":
            case "System.Boolean":
            case "byte":
            case "System.Byte":
            case "sbyte":
            case "System.SByte":
                size = 1; return true;
            case "short":
            case "System.Int16":
            case "ushort":
            case "System.UInt16":
            case "char":
            case "System.Char":
                size = 2; return true;
            case "int":
            case "System.Int32":
            case "uint":
            case "System.UInt32":
            case "float":
            case "System.Single":
                size = 4; return true;
            case "long":
            case "System.Int64":
            case "ulong":
            case "System.UInt64":
            case "double":
            case "System.Double":
            case "System.DateTime":
            case "System.TimeSpan":
                size = 8; return true;
            case "decimal":
            case "System.Decimal":
            case "System.Guid":
                size = 16; return true;
            default:
                size = 0; return false;
        }
    }
}
