namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateSharpPackIntegration(SharpPackIntegrationAnalysisResult analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0618");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using SharpLink.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace SharpLink.Generated;");
        sb.AppendLine();

        foreach (var sidecar in analysis.Sidecars)
            AppendSharpPackSidecar(sb, sidecar);

        sb.AppendLine("internal static class __SharpLinkGeneratedSharpPackIntegration");
        sb.AppendLine("{");
        sb.AppendLine("    internal static void Configure(IRpcCodecAdapterScope adapterScope)");
        sb.AppendLine("    {");
        if (analysis.Sidecars.IsDefaultOrEmpty)
        {
            sb.AppendLine("        _ = adapterScope;");
        }
        else
        {
            var identity = GetSharpPackConfigurationIdentity(analysis.Sidecars);
            sb.AppendLine("        if (adapterScope is not global::SharpLink.Serializer.SharpPack.ISharpPackRpcCodecAdapterScopeConfiguration configurable)");
            sb.AppendLine("            throw new InvalidOperationException(\"SharpPack adapter scope does not support generated Contract formatter configuration.\");");
            sb.AppendLine($"        configurable.Configure(\"slsp/{identity}\", static builder =>");
            sb.AppendLine("        {");
            foreach (var sidecar in analysis.Sidecars)
            {
                sb.AppendLine($"            builder.Register<{sidecar.TypeName}>(new {sidecar.FormatterName}());");
            }
            sb.AppendLine("        });");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetSharpPackConfigurationIdentity(
        ImmutableArray<SharpPackSidecarModel> sidecars)
    {
        var parts = sidecars.Select(static sidecar => string.Join(
            ";",
            sidecar.TypeName,
            sidecar.IsReferenceType ? "ref" : "value",
            string.Join(",", sidecar.Members.Select(static member =>
                $"{member.Order}:{member.Name}:{member.TypeName}")),
            "ctor=" + string.Join(",", sidecar.ConstructorMembers)));
        return Hashing.GetIdentifierHash(string.Join("|", parts));
    }

    private static void AppendSharpPackSidecar(StringBuilder sb, SharpPackSidecarModel sidecar)
    {
        var nullableSuffix = sidecar.IsReferenceType ? "?" : string.Empty;
        sb.AppendLine($"internal sealed class {sidecar.FormatterName} : global::SharpPack.SharpPackFormatter<{sidecar.TypeName}>");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Serialize<TBufferWriter>(");
        sb.AppendLine("        ref global::SharpPack.SharpPackWriter<TBufferWriter> writer,");
        sb.AppendLine($"        scoped ref {sidecar.TypeName}{nullableSuffix} value)");
        sb.AppendLine("    {");
        if (sidecar.IsReferenceType)
        {
            sb.AppendLine("        if (value is null)");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNullObjectHeader();");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
        }
        sb.AppendLine($"        writer.WriteObjectHeader({sidecar.Members.Length});");
        foreach (var member in sidecar.Members)
        {
            sb.AppendLine($"        writer.WriteValue<{member.TypeName}>(value{(sidecar.IsReferenceType ? "!" : string.Empty)}.{member.Identifier});");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override void Deserialize(");
        sb.AppendLine("        ref global::SharpPack.SharpPackReader reader,");
        sb.AppendLine($"        scoped ref {sidecar.TypeName}{nullableSuffix} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!reader.TryReadObjectHeader(out var count))");
        sb.AppendLine("        {");
        sb.AppendLine("            value = default!;");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine($"        if (count > {sidecar.Members.Length})");
        sb.AppendLine($"            global::SharpPack.SharpPackSerializationException.ThrowInvalidPropertyCount(typeof({sidecar.TypeName}), {sidecar.Members.Length}, count);");
        sb.AppendLine();
        for (var index = 0; index < sidecar.Members.Length; index++)
        {
            var member = sidecar.Members[index];
            sb.AppendLine($"        {member.TypeName} __slsp_{index} = default!;");
            sb.AppendLine($"        if (count > {index})");
            sb.AppendLine($"            __slsp_{index} = reader.ReadValue<{member.TypeName}>();");
        }
        if (sidecar.Members.Length != 0)
            sb.AppendLine();

        var indexByName = sidecar.Members
            .Select((member, index) => (member.Name, Index: index))
            .ToDictionary(static item => item.Name, static item => item.Index, StringComparer.Ordinal);
        var constructorArguments = sidecar.ConstructorMembers
            .Select(name => "__slsp_" + indexByName[name])
            .ToArray();
        var constructorSet = new HashSet<string>(sidecar.ConstructorMembers, StringComparer.Ordinal);
        var initializerMembers = sidecar.Members
            .Where(member => !constructorSet.Contains(member.Name))
            .ToArray();

        sb.Append($"        value = new {sidecar.TypeName}({string.Join(", ", constructorArguments)})");
        if (initializerMembers.Length == 0)
        {
            sb.AppendLine(";");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine("        {");
            foreach (var member in initializerMembers)
            {
                sb.AppendLine($"            {member.Identifier} = __slsp_{indexByName[member.Name]},");
            }
            sb.AppendLine("        };");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}
