namespace SharpLink.Generator;

public partial class RpcGenerator
{
    private static string GenerateProxy(RpcInterfaceModel model)
    {
        var nsDeclaration = string.IsNullOrEmpty(model.Namespace) ? "" : $"namespace {model.Namespace};";

        var sb = new StringBuilder();
        sb.AppendLine($$"""
                        // <auto-generated/>
                        #nullable enable
                        using SharpLink.Abstractions;
                        using SharpLink.Runtime;
                        using System;
                        using System.Buffers;
                        using System.Buffers.Binary;
                        using System.Collections.Generic;
                        using System.Runtime.CompilerServices;
                        using System.Threading;
                        using System.Threading.Tasks;

                        {{nsDeclaration}}

                        public class {{model.Name}}_Proxy(IRpcChannel channel) : {{model.FullName}}
                        {
                            const long _interfaceHash = {{model.Hash}}L;
                        """);

        AppendSizeFieldsByType(sb, model.Methods);

        foreach (var method in model.Methods)
        {
            var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var streamParams = method.Parameters.Where(p => p.IsStream).ToList();
            var payloadParams = method.Parameters.Where(p => !p.IsStream && !p.IsCancellationToken).ToList();
            var cancellationTokenParam = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
            var cancellationTokenArg = cancellationTokenParam is null ? "default" : cancellationTokenParam.Name;
            var blittablePayloadParams = payloadParams.Where(p => p.IsBlittable).ToList();
            var complexPayloadParams = payloadParams.Where(p => !p.IsBlittable).ToList();

            sb.AppendLine($"    public {(method.IsStreamReturn ? method.ReturnType : $"async {method.ReturnType}")} {method.Name}({paramList})");
            sb.AppendLine("    {");
            if (payloadParams.Count > 0)
            {
                sb.AppendLine("        Action<ArrayBufferWriter<byte>> payloadWriter = (writer) =>");
                sb.AppendLine("        {");

                if (blittablePayloadParams.Count > 0)
                {
                    var totalExpr = string.Join(" + ", blittablePayloadParams.Select(p => GetSizeToken(p.Type)));
                    sb.AppendLine($"            var fixedSize = {totalExpr};");
                    sb.AppendLine("            var fixedSpan = writer.GetSpan(fixedSize);");
                    sb.AppendLine("            var fixedOffset = 0;");
                    foreach (var p in blittablePayloadParams)
                    {
                        var sizeToken = GetSizeToken(p.Type);
                        sb.AppendLine($"            System.Runtime.CompilerServices.Unsafe.WriteUnaligned(ref System.Runtime.InteropServices.MemoryMarshal.GetReference(fixedSpan.Slice(fixedOffset, {sizeToken})), {p.Name});");
                        sb.AppendLine($"            fixedOffset += {sizeToken};");
                    }
                    sb.AppendLine("            writer.Advance(fixedSize);");
                }

                foreach (var p in complexPayloadParams)
                {
                    sb.AppendLine("            int lenOffset = writer.WrittenCount;");
                    sb.AppendLine("            writer.Advance(4);");
                    sb.AppendLine("            int start = writer.WrittenCount;");
                    sb.AppendLine($"            SharpLink.Runtime.RpcCodec.Serialize({p.Name}, writer);");
                    sb.AppendLine("            int len = writer.WrittenCount - start;");
                    sb.AppendLine("            var span = System.Runtime.InteropServices.MemoryMarshal.AsMemory(writer.WrittenMemory).Span;");
                    sb.AppendLine("            var lengthSlice = span.Slice(lenOffset, 4);");
                    sb.AppendLine("            BinaryPrimitives.WriteInt32LittleEndian(lengthSlice, len);");
                }

                sb.AppendLine("        };");
            }

            var hasPayload = payloadParams.Count > 0;
            var hasStream = streamParams.Count > 0;
            var timeoutArg = method.TimeoutSeconds is { } seconds
                ? $", TimeSpan.FromSeconds({seconds.ToString("R", InvariantCulture)}d)"
                : "";
            var hasTimeout = method.HasTimeoutAttribute;
            var hasTimeoutOverride = method.TimeoutSeconds is not null;

            string SelectByTimeout(string noTimeoutCall, string defaultTimeoutCall, string explicitTimeoutCall)
            {
                if (!hasTimeout)
                    return noTimeoutCall;
                return hasTimeoutOverride ? explicitTimeoutCall : defaultTimeoutCall;
            }

            if (hasStream)
            {
                sb.AppendLine("        Func<long, CancellationToken, Task> streamSender = async (requestId, cancellationToken) =>");
                sb.AppendLine("        {");
                if (streamParams.Count == 1)
                {
                    sb.AppendLine($"            await channel.SendClientStreamAsync(requestId, (sbyte)1, {streamParams[0].Name}, cancellationToken);");
                }
                else if (streamParams.Count == 2)
                {
                    sb.AppendLine($"            var task1 = channel.SendClientStreamAsync(requestId, (sbyte)1, {streamParams[0].Name}, cancellationToken);");
                    sb.AppendLine($"            var task2 = channel.SendClientStreamAsync(requestId, (sbyte)2, {streamParams[1].Name}, cancellationToken);");
                    sb.AppendLine("            await Task.WhenAll(task1, task2);");
                }
                else if (streamParams.Count == 3)
                {
                    sb.AppendLine($"            var task1 = channel.SendClientStreamAsync(requestId, (sbyte)1, {streamParams[0].Name}, cancellationToken);");
                    sb.AppendLine($"            var task2 = channel.SendClientStreamAsync(requestId, (sbyte)2, {streamParams[1].Name}, cancellationToken);");
                    sb.AppendLine($"            var task3 = channel.SendClientStreamAsync(requestId, (sbyte)3, {streamParams[2].Name}, cancellationToken);");
                    sb.AppendLine("            await Task.WhenAll(task1, task2, task3);");
                }
                else
                {
                    var streamId = 1;
                    foreach (var streamParam in streamParams)
                    {
                        sb.AppendLine($"            await channel.SendClientStreamAsync(requestId, (sbyte){streamId}, {streamParam.Name}, cancellationToken);");
                        streamId++;
                    }
                }
                sb.AppendLine("        };");
            }

            if (method.IsStreamReturn)
            {
                if (hasStream)
                {
                    sb.AppendLine(hasPayload
                        ? method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return channel.InvokeCancellableDuplexStreamAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableDuplexStreamWithDefaultTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableDuplexStreamWithTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return channel.InvokeDuplexStreamAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                $"        return channel.InvokeCancellableDuplexStreamWithDefaultTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                $"        return channel.InvokeCancellableDuplexStreamWithTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg});")
                        : method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return channel.InvokeCancellableDuplexStreamNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableDuplexStreamWithDefaultTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableDuplexStreamWithTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, streamSender{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return channel.InvokeDuplexStreamNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, streamSender);",
                                $"        return channel.InvokeCancellableDuplexStreamWithDefaultTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, streamSender);",
                                $"        return channel.InvokeCancellableDuplexStreamWithTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, streamSender{timeoutArg});"));
                }
                else
                {
                    sb.AppendLine(hasPayload
                        ? method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return channel.InvokeCancellableServerStreamAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableServerStreamWithDefaultTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableServerStreamWithTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return channel.InvokeServerStreamAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter);",
                                $"        return channel.InvokeCancellableServerStreamWithDefaultTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter);",
                                $"        return channel.InvokeCancellableServerStreamWithTimeoutAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg});")
                        : method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return channel.InvokeCancellableServerStreamNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableServerStreamWithDefaultTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                $"        return channel.InvokeCancellableServerStreamWithTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return channel.InvokeServerStreamNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L);",
                                $"        return channel.InvokeCancellableServerStreamWithDefaultTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L);",
                                $"        return channel.InvokeCancellableServerStreamWithTimeoutNoPayloadAsync<{method.StreamItemType}>(_interfaceHash, {method.Hash}L{timeoutArg});"));
                }
            }
            else if (method.IsVoid)
            {
                if (method.IsOneWay)
                {
                    if (hasStream)
                    {
                        sb.AppendLine(hasPayload
                            ? method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableOneWayClientStreamAsync(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithDefaultTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeOneWayClientStreamAsync(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithDefaultTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg});")
                            : method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableOneWayClientStreamNoPayloadAsync(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithDefaultTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L, streamSender{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeOneWayClientStreamNoPayloadAsync(_interfaceHash, {method.Hash}L, streamSender);",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithDefaultTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L, streamSender);",
                                    $"        await channel.InvokeCancellableOneWayClientStreamWithTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L, streamSender{timeoutArg});"));
                    }
                    else
                    {
                        sb.AppendLine(hasPayload
                            ? method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableOneWayAsync(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayWithDefaultTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayWithTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeOneWayAsync(_interfaceHash, {method.Hash}L, payloadWriter);",
                                    $"        await channel.InvokeCancellableOneWayWithDefaultTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter);",
                                    $"        await channel.InvokeCancellableOneWayWithTimeoutAsync(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg});")
                            : method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableOneWayNoPayloadAsync(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayWithDefaultTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableOneWayWithTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeOneWayNoPayloadAsync(_interfaceHash, {method.Hash}L);",
                                    $"        await channel.InvokeCancellableOneWayWithDefaultTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L);",
                                    $"        await channel.InvokeCancellableOneWayWithTimeoutNoPayloadAsync(_interfaceHash, {method.Hash}L{timeoutArg});"));
                    }
                }
                else
                {
                    if (hasStream)
                    {
                        sb.AppendLine(hasPayload
                            ? method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableClientStreamNoReturnAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithDefaultTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeClientStreamNoReturnAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithDefaultTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg});")
                            : method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableClientStreamNoReturnNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithDefaultTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, streamSender{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeClientStreamNoReturnNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, streamSender);",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithDefaultTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, streamSender);",
                                    $"        await channel.InvokeCancellableClientStreamNoReturnWithTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, streamSender{timeoutArg});"));
                    }
                    else
                    {
                        sb.AppendLine(hasPayload
                            ? method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableNoReturnAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableNoReturnWithDefaultTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableNoReturnWithTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeNoReturnAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter);",
                                    $"        await channel.InvokeCancellableNoReturnWithDefaultTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter);",
                                    $"        await channel.InvokeCancellableNoReturnWithTimeoutAsync<byte>(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg});")
                            : method.HasCancellationToken
                                ? SelectByTimeout(
                                    $"        await channel.InvokeCancellableNoReturnNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableNoReturnWithDefaultTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                    $"        await channel.InvokeCancellableNoReturnWithTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L{timeoutArg}, {cancellationTokenArg});")
                                : SelectByTimeout(
                                    $"        await channel.InvokeNoReturnNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L);",
                                    $"        await channel.InvokeCancellableNoReturnWithDefaultTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L);",
                                    $"        await channel.InvokeCancellableNoReturnWithTimeoutNoPayloadAsync<byte>(_interfaceHash, {method.Hash}L{timeoutArg});"));
                    }
                }
            }
            else
            {
                if (hasStream)
                {
                    sb.AppendLine(hasPayload
                        ? method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return await channel.InvokeCancellableClientStreamAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableClientStreamWithDefaultTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableClientStreamWithTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return await channel.InvokeClientStreamAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                $"        return await channel.InvokeCancellableClientStreamWithDefaultTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender);",
                                $"        return await channel.InvokeCancellableClientStreamWithTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, streamSender{timeoutArg});")
                        : method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return await channel.InvokeCancellableClientStreamNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableClientStreamWithDefaultTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, streamSender, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableClientStreamWithTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, streamSender{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return await channel.InvokeClientStreamNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, streamSender);",
                                $"        return await channel.InvokeCancellableClientStreamWithDefaultTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, streamSender);",
                                $"        return await channel.InvokeCancellableClientStreamWithTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, streamSender{timeoutArg});"));
                }
                else
                {
                    sb.AppendLine(hasPayload
                        ? method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return await channel.InvokeCancellableAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableWithDefaultTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableWithTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return await channel.InvokeAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter);",
                                $"        return await channel.InvokeCancellableWithDefaultTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter);",
                                $"        return await channel.InvokeCancellableWithTimeoutAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, payloadWriter{timeoutArg});")
                        : method.HasCancellationToken
                            ? SelectByTimeout(
                                $"        return await channel.InvokeCancellableNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableWithDefaultTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L, {cancellationTokenArg});",
                                $"        return await channel.InvokeCancellableWithTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L{timeoutArg}, {cancellationTokenArg});")
                            : SelectByTimeout(
                                $"        return await channel.InvokeNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L);",
                                $"        return await channel.InvokeCancellableWithDefaultTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L);",
                                $"        return await channel.InvokeCancellableWithTimeoutNoPayloadAsync<{method.GenericArgumentType}>(_interfaceHash, {method.Hash}L{timeoutArg});"));
                }
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine($$"""

                        internal static class {{model.Name}}_ProxyRegistration
                        {
                            [ModuleInitializer]
                            internal static void Register()
                            {
                                SharpLink.Abstractions.GeneratedProxyRegistry.Register(typeof({{model.FullName}}), (channel) => new {{model.Name}}_Proxy(channel));
                            }
                        }
                        """);
        return sb.ToString();
    }

}
