<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../src/SharpLink.Sdk/SharpLink.Sdk.csproj" />
    <ProjectReference Include="../../../../../src/SharpLink.Client/SharpLink.Client.csproj" />
    <ProjectReference Include="../../../../../src/SharpLink.Server/SharpLink.Server.csproj" />
    <ProjectReference Include="../../../../../src/SharpLink.Serializer.SharpPack/SharpLink.Serializer.SharpPack.csproj" />
    <ProjectReference Include="../../../../../src/SharpLink.Generator/SharpLink.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
