<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>SharpLink.Benchmarks</AssemblyName>
    <RootNamespace>SharpLink.Benchmarks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpLink.Abstractions\SharpLink.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Client\SharpLink.Client.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Runtime\SharpLink.Runtime.csproj" />
  </ItemGroup>
</Project>
