<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SharpLink.Compression.Zstd</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpLink.Runtime\SharpLink.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>
</Project>
