<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <AssemblyName>SharpLink.NewGeneratorOldAbstractions</AssemblyName>
    <SharpLinkCurrentVersion Condition="'$(SharpLinkCurrentVersion)' == ''">2.0.0</SharpLinkCurrentVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpLink.Sdk" Version="[$(SharpLinkCurrentVersion)]" />
    <PackageReference Include="SharpLink.Abstractions" Version="[1.1.1]" />
  </ItemGroup>
</Project>
