#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description="Enforce SharpLink maintainability file-LOC debt baseline.")
    parser.add_argument("--report", required=True, help="Path to report.json generated by report-maintainability.sh.")
    parser.add_argument("--baseline", required=True, help="Path to the checked-in maintainability baseline JSON.")
    return parser.parse_args()


def load_json(path: Path):
    try:
        with path.open("r", encoding="utf-8") as stream:
            return json.load(stream)
    except FileNotFoundError:
        raise ValueError(f"file not found: {path}")
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON in {path}: {exc}")


def require_int(value, description):
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"{description} must be an integer")
    return value


def main():
    args = parse_args()
    report_path = Path(args.report)
    baseline_path = Path(args.baseline)

    try:
        report = load_json(report_path)
        baseline = load_json(baseline_path)

        if require_int(baseline.get("schemaVersion"), "baseline schemaVersion") != 1:
            raise ValueError("unsupported baseline schemaVersion; expected 1")

        rules = baseline.get("rules")
        if not isinstance(rules, dict):
            raise ValueError("baseline rules must be an object")

        thresholds = {}
        for domain in ("source", "test"):
            rule = rules.get(domain)
            if not isinstance(rule, dict):
                raise ValueError(f"baseline rules.{domain} must be an object")
            threshold = require_int(rule.get("maxFileLoc"), f"baseline rules.{domain}.maxFileLoc")
            if threshold <= 0:
                raise ValueError(f"baseline rules.{domain}.maxFileLoc must be positive")
            thresholds[domain] = threshold

        report_files = report.get("files")
        if not isinstance(report_files, list):
            raise ValueError("report files must be an array")

        current = {}
        for index, item in enumerate(report_files):
            if not isinstance(item, dict):
                raise ValueError(f"report files[{index}] must be an object")
            domain = item.get("domain")
            path = item.get("path")
            loc = require_int(item.get("loc"), f"report files[{index}].loc")
            if domain not in thresholds:
                raise ValueError(f"report files[{index}].domain must be source or test")
            if not isinstance(path, str) or not path:
                raise ValueError(f"report files[{index}].path must be a non-empty string")
            key = (domain, path)
            if key in current:
                raise ValueError(f"duplicate report file entry: {domain}:{path}")
            current[key] = loc

        raw_allowances = baseline.get("allowances")
        if not isinstance(raw_allowances, list):
            raise ValueError("baseline allowances must be an array")

        allowances = {}
        for index, item in enumerate(raw_allowances):
            if not isinstance(item, dict):
                raise ValueError(f"baseline allowances[{index}] must be an object")
            domain = item.get("domain")
            path = item.get("path")
            max_loc = require_int(item.get("maxLoc"), f"baseline allowances[{index}].maxLoc")
            reason = item.get("reason")
            if domain not in thresholds:
                raise ValueError(f"baseline allowances[{index}].domain must be source or test")
            if not isinstance(path, str) or not path:
                raise ValueError(f"baseline allowances[{index}].path must be a non-empty string")
            if not isinstance(reason, str) or not reason.strip():
                raise ValueError(f"baseline allowances[{index}].reason must be a non-empty string")
            if max_loc <= thresholds[domain]:
                raise ValueError(
                    f"baseline allowance {domain}:{path} has maxLoc {max_loc}, "
                    f"which does not exceed the {thresholds[domain]} LOC threshold"
                )
            key = (domain, path)
            if key in allowances:
                raise ValueError(f"duplicate baseline allowance: {domain}:{path}")
            allowances[key] = max_loc

    except ValueError as exc:
        print(f"Maintainability baseline configuration error: {exc}", file=sys.stderr)
        return 2

    violations = []
    for (domain, path), loc in sorted(current.items()):
        threshold = thresholds[domain]
        if loc <= threshold:
            continue

        allowance = allowances.get((domain, path))
        if allowance is None:
            violations.append(
                f"{domain} file LOC: {path} is {loc} LOC; threshold is {threshold} LOC "
                "and no baseline allowance exists."
            )
        elif loc > allowance:
            violations.append(
                f"{domain} file LOC regression: {path} is {loc} LOC; "
                f"baseline allowance is {allowance} LOC."
            )

    for (domain, path), allowance in sorted(allowances.items()):
        loc = current.get((domain, path))
        if loc is None:
            violations.append(
                f"stale baseline allowance: {domain}:{path} is allowed up to {allowance} LOC "
                "but the file is no longer present in the report."
            )
            continue
        threshold = thresholds[domain]
        if loc <= threshold:
            violations.append(
                f"obsolete baseline allowance: {domain}:{path} is now {loc} LOC, "
                f"at or below the {threshold} LOC threshold; remove the allowance."
            )

    if violations:
        print("Maintainability debt gate failed:", file=sys.stderr)
        for violation in violations:
            print(f"- {violation}", file=sys.stderr)
        print(
            f"\nRemediation: reduce the file below its domain threshold, or intentionally update "
            f"{baseline_path.as_posix()} with a reviewed maxLoc and reason. "
            "Baseline changes should explain why the exception is necessary.",
            file=sys.stderr,
        )
        return 1

    oversized = sum(1 for (domain, _), loc in current.items() if loc > thresholds[domain])
    print(
        "Maintainability debt gate passed: "
        f"{len(current)} files checked, {oversized} historical oversized files within baseline allowances."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
