<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\SharpLink.Abstractions\SharpLink.Abstractions.csproj" />
    <ProjectReference Include="..\SharpLink.Client\SharpLink.Client.csproj" />
    <ProjectReference Include="..\SharpLink.Server\SharpLink.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
</Project>
