<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpLink.Compression.Zstd\SharpLink.Compression.Zstd.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Runtime\SharpLink.Runtime.csproj" />
  </ItemGroup>
</Project>
