<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpLink.Abstractions\SharpLink.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Server\SharpLink.Server.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Client\SharpLink.Client.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Runtime\SharpLink.Runtime.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Sdk\SharpLink.Sdk.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Serializer.SharpPack\SharpLink.Serializer.SharpPack.csproj" />
    <ProjectReference Include="..\..\src\SharpLink.Generator\SharpLink.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\SharpLink.DynamicContracts\SharpLink.DynamicContracts.csproj" />
    <ProjectReference Include="..\SharpLink.DynamicServices\SharpLink.DynamicServices.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\SharpLink.LoadTestBase\SharpLink.LoadTestBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SharpLink.DynamicServices\bin\$(Configuration)\$(TargetFramework)\SharpLink.DynamicPlugin.Services.dll"
          Link="SharpLink.DynamicPlugin.Services.dll"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="SharpPack" />
  </ItemGroup>
</Project>
